// FILE: script.js

// --- Firebase Firestore Imports (MUST be at the top of the file) ---
// These specific Firestore functions are needed for database operations like adding, querying, and getting documents.
import { collection, addDoc, query, where, getDocs } from "https://www.gstatic.com/firebasejs/11.6.1/firebase-firestore.js";

// --- 1. Game State Variables ---
let currentSeedWord = "";
let currentTargetWord = "";
let currentChain = [];
let currentDifficulty = "N/A";
let optimalPathLength = 0;
let targetTransitionsForScoring = 0;
let powerUpCounts = { hint: 0, swap: 0, skip: 0 }; // Tracks AVAILABLE power-ups (reset on new game)
let powerUpsUsedThisGame = { hint: 0, swap: 0, skip: 0 }; // Tracks power-ups *ACTUALLY USED* in the current game (reset on new game)
let currentScore = 0;
let gameTimer = 0;
let timerInterval = null;
let gameInProgress = false;
let inTutorialMode = false; // New flag to track if tutorial was opened mid-game
// --- Curated List of Random Puzzles (for "Play Random Puzzle" feature) ---
// All puzzles are 4-letter words, with optimal path lengths of 2 or more.
// Difficulty is based on optimal path length: Easy (2-3), Medium (4-5), Hard (6+)
const RANDOM_PUZZLES = [
    // --- Original Puzzles (Verified) ---
    { start_word: "CAT", target_word: "DOG", optimal_path_length: 3, optimal_path: ["CAT", "COT", "COG", "DOG"], difficulty: "Easy" },
    { start_word: "WAVE", target_word: "DIVE", optimal_path_length: 2, optimal_path: ["WAVE", "DAVE", "DIVE"], difficulty: "Easy" },
    { start_word: "COLD", target_word: "WARM", optimal_path_length: 4, optimal_path: ["COLD", "CORD", "WORD", "WORM", "WARM"], difficulty: "Medium" },
    { start_word: "PINE", target_word: "SALT", optimal_path_length: 4, optimal_path: ["PINE", "PANE", "SANE", "SALE", "SALT"], difficulty: "Medium" },
    { start_word: "GAME", target_word: "HOME", optimal_path_length: 3, optimal_path: ["GAME", "DAME", "DOME", "HOME"], difficulty: "Easy" },
    { start_word: "STAY", target_word: "PLAY", optimal_path_length: 2, optimal_path: ["STAY", "SLAY", "PLAY"], difficulty: "Easy" },
    { start_word: "READ", target_word: "ROSE", optimal_path_length: 6, optimal_path: ["READ", "HEAD", "HELD", "HOLD", "HOLE", "ROLE", "ROSE"], difficulty: "Hard" },
    { start_word: "HEMP", target_word: "FLIP", optimal_path_length: 6, optimal_path: ["HEMP", "HEAP", "HEAT", "FEAT", "FLAT", "FLAP", "FLIP"], difficulty: "Hard" },
    { start_word: "BOWS", target_word: "LICK", optimal_path_length: 5, optimal_path: ["BOWS", "LOWS", "LOOS", "LOOK", "LOCK", "LICK"], difficulty: "Medium" },

    // --- New Puzzles (Generated by you, verified by me) ---
    { start_word: "GEAR", target_word: "FRET", optimal_path_length: 4, optimal_path: ["GEAR", "FEAR", "FEAT", "FEET", "FRET"], difficulty: "Medium" },
    { start_word: "PITS", target_word: "PLED", optimal_path_length: 3, optimal_path: ["PITS", "PIES", "PIED", "PLED"], difficulty: "Medium" },
    { start_word: "TUSK", target_word: "LIFT", optimal_path_length: 5, optimal_path: ["TUSK", "RUSK", "RUST", "LUST", "LIST", "LIFT"], difficulty: "Medium" },
    { start_word: "WADS", target_word: "PARE", optimal_path_length: 3, optimal_path: ["WADS", "WADE", "WARE", "PARE"], difficulty: "Easy" },
    { start_word: "FELT", target_word: "PIER", optimal_path_length: 5, optimal_path: ["FELT", "FEAT", "FEAR", "PEAR", "PEER", "PIER"], difficulty: "Medium" },
    { start_word: "CHIC", target_word: "GOAD", optimal_path_length: 5, optimal_path: ["CHIC", "CHIT", "CHAT", "COAT", "GOAT", "GOAD"], difficulty: "Medium" },
    { start_word: "LUCK", target_word: "DOLE", optimal_path_length: 6, optimal_path: ["LUCK", "BUCK", "BULK", "BULL", "DULL", "DOLL", "DOLE"], difficulty: "Hard" },
    { start_word: "SILK", target_word: "HURL", optimal_path_length: 4, optimal_path: ["SILK", "SILL", "HILL", "HULL", "HURL"], difficulty: "Medium" },
    { start_word: "SLAM", target_word: "FOUL", optimal_path_length: 5, optimal_path: ["SLAM", "SLUM", "SLUR", "SOUR", "FOUR", "FOUL"], difficulty: "Medium" },
    { start_word: "FOOD", target_word: "WINE", optimal_path_length: 4, optimal_path: ["FOOD", "FOND", "FIND", "FINE", "WINE"], difficulty: "Medium" },
    { start_word: "TOOK", target_word: "STAY", optimal_path_length: 6, optimal_path: ["TOOK", "BOOK", "BOOR", "BOAR", "SOAR", "STAR", "STAY"], difficulty: "Hard" },
    { start_word: "NEXT", target_word: "LIFT", optimal_path_length: 5, optimal_path: ["NEXT", "NEAT", "HEAT", "HEFT", "LEFT", "LIFT"], difficulty: "Medium" },
    { start_word: "WINE", target_word: "HOLE", optimal_path_length: 4, optimal_path: ["WINE", "DINE", "DONE", "DOLE", "HOLE"], difficulty: "Medium" },
    { start_word: "YIPS", target_word: "LOVE", optimal_path_length: 5, optimal_path: ["YIPS", "RIPS", "RIPE", "ROPE", "LOPE", "LOVE"], difficulty: "Medium" },
    { start_word: "POEM", target_word: "YAPS", optimal_path_length: 7, optimal_path: ["POEM", "POET", "PORT", "PART", "CART", "CARS", "CAPS", "YAPS"], difficulty: "Hard" },
    { start_word: "PLOT", target_word: "CALM", optimal_path_length: 8, optimal_path: ["PLOT", "BLOT", "BOOT", "HOOT", "HOLT", "HALT", "HALL", "CALL", "CALM"], difficulty: "Hard" },
    { start_word: "SAND", target_word: "TENT", optimal_path_length: 3, optimal_path: ['SAND', 'SEND', 'SENT', 'TENT'], difficulty: "Easy" },
    { start_word: "CONS", target_word: "BOTH", optimal_path_length: 3, optimal_path: ['CONS', 'COTS', 'BOTS', 'BOTH'], difficulty: "Easy" },
    { start_word: "HOOD", target_word: "COAT", optimal_path_length: 3, optimal_path: ['HOOD', 'HOOT', 'COOT', 'COAT'], difficulty: "Easy" },
    { start_word: "FEAT", target_word: "SELL", optimal_path_length: 3, optimal_path: ['FEAT', 'SEAT', 'SEAL', 'SELL'], difficulty: "Easy" },
    { start_word: "DANK", target_word: "TUNE", optimal_path_length: 3, optimal_path: ['DANK', 'DUNK', 'DUNE', 'TUNE'], difficulty: "Easy" },
    { start_word: "HOLT", target_word: "BANK", optimal_path_length: 5, optimal_path: ['HOLT', 'HOLD', 'BOLD', 'BALD', 'BAND', 'BANK'], difficulty: "Medium" },
    { start_word: "FLIP", target_word: "HOOP", optimal_path_length: 4, optimal_path: ['FLIP', 'FLOP', 'CLOP', 'COOP', 'HOOP'], difficulty: "Medium" },
    { start_word: "HOOT", target_word: "DIVE", optimal_path_length: 5, optimal_path: ['HOOT', 'HOST', 'HOSE', 'DOSE', 'DOVE', 'DIVE'], difficulty: "Medium" },
    { start_word: "MINK", target_word: "LAST", optimal_path_length: 4, optimal_path: ['MINK', 'MINT', 'LINT', 'LIST', 'LAST'], difficulty: "Medium" },
    { start_word: "PART", target_word: "HIND", optimal_path_length: 4, optimal_path: ['PART', 'PANT', 'PINT', 'HINT', 'HIND'], difficulty: "Medium" },
    { start_word: "LOOP", target_word: "PUNK", optimal_path_length: 5, optimal_path: ['LOOP', 'LOOK', 'BOOK', 'BONK', 'BUNK', 'PUNK'], difficulty: "Medium" },
    { start_word: "GRAD", target_word: "ACID", optimal_path_length: 3, optimal_path: ['GRAD', 'GRID', 'ARID', 'ACID'], difficulty: "Medium" },
    { start_word: "SLUM", target_word: "FLAN", optimal_path_length: 4, optimal_path: ['SLUM', 'SLAM', 'CLAM', 'CLAN', 'FLAN'], difficulty: "Medium" },
    { start_word: "FAME", target_word: "BUYS", optimal_path_length: 7, optimal_path: ['FAME', 'LAME', 'LANE', 'CANE', 'CANS', 'BANS', 'BAYS', 'BUYS'], difficulty: "Hard" },
    { start_word: "SEAM", target_word: "CZAR", optimal_path_length: 4, optimal_path: ['SEAM', 'SHAM', 'SHAR', 'CHAR', 'CZAR'], difficulty: "Medium" },
];


// --- 2. Game Elements (Get References from HTML) ---
const seedWordDisplay = document.getElementById('seed-word-display');
const targetWordDisplay = document.getElementById('target-word-display');
const difficultyDisplay = document.getElementById('difficulty-display');
const wordChainList = document.getElementById('word-chain-list');
const userGuessInput = document.getElementById('user-guess-input');
const submitGuessBtn = document.getElementById('submit-guess-btn');
const currentScoreDisplay = document.getElementById('current-score');
const timerDisplay = document.getElementById('timer-display');
const hintCountDisplay = document.getElementById('hint-count');
const swapCountDisplay = document.getElementById('swap-count');
const skipCountDisplay = document.getElementById('skip-count');
const hintBtn = document.getElementById('hint-btn');
const swapBtn = document.getElementById('swap-btn');
const skipBtn = document.getElementById('skip-btn');
const leaderboardList = document.getElementById('leaderboard-list');
const newGameBtn = document.getElementById('new-game-btn');
const tutorialModal = document.getElementById('tutorial-modal');
const tutorialTitle = document.getElementById('tutorial-title');
const tutorialText = document.getElementById('tutorial-text');
const tutorialNextBtn = document.getElementById('tutorial-next-btn');
const tutorialSkipBtn = document.getElementById('tutorial-skip-btn');
const randomPuzzleBtn = document.getElementById('random-puzzle-btn');
const optimalPathDisplaySection = document.getElementById('optimal-path-display-section');
const optimalPathList = document.getElementById('optimal-path-list');
const howToPlayBtn = document.getElementById('how-to-play-btn');
const replayPuzzleBtn = document.getElementById('replay-puzzle-btn');
const giveUpBtn = document.getElementById('give-up-btn');
const viewSolutionBtn = document.getElementById('view-solution-btn'); // Add this new line
const shareResultBtn = document.getElementById('share-result-btn');

// --- 3. Game Dictionary (Crucial for Word Validation) ---
const dictionary = [
    "READ", "HEAD", "HELD", "HOLD", "HOLE", "ROLE", "ROSE", // For testing READ-ROSE
    "WAVE", "DAVE", "DIVE", "WANE", "WINE", "DINE",           // For testing WAVE-DIVE
    "CAT", "COT", "COG", "DOG",                               // For testing CAT-DOG
    "MAKE", "TAKE",
    "COLD", "CORD", "WORD", "WORM", "WARM",
    "PINE", "PANE", "SANE", "SALE", "SALT",
    "LIME", "LIMP", "SIMP", "SUMP", "PUMP", "POMP", "POOP", "COOP", "COUP", "SOUP",
    "BALE", "BALD", "BOLD", "COLD",
    "FLAME", "BLAME", "BLASE", "BLAST",
    "GAME", "DAME", "DOME", "HOME",
    "STAY", "SLAY", "PLAY",
    "FLAM",
    // --- Full Dictionary (Expanded for robustness) ---
    "AAHS", "AALS", "ABAS", "ABBA", "ABBE", "ABED", "ABER", "ABET", "ABLE", "ABLY", "ABOS", "ABRI", "ABUT", "ABYE", "ABYS", "ACED", "ACES", "ACHE", "ACHY", "ACID", "ACME", "ACNE", "ACRE", "ACTA", "ACTS", "ACYL", "ADDS", "ADIT", "ADOS", "ADZE", "AEON", "AERO", "AERY", "AFAR", "AFRO", "AGAR", "AGAS", "AGED", "AGEE", "AGER", "AGES", "AGHA", "AGIN", "AGIO", "AGLY", "AGMA", "AGOG", "AGON", "AGUE", "AHED", "AHEM", "AHIS", "AHOY", "AIDE", "AIDS", "AILS", "AIMS", "AINS", "AIRN", "AIRS", "AIRT", "AIRY", "AITS", "AJAR", "AJEE", "AKEE", "AKIN", "ALAE", "ALAN", "ALAR", "ALAS", "ALBA", "ALBS", "ALEC", "ALEE", "ALEF", "ALES", "ALFA", "ALGA", "ALIF", "ALIT", "ALKY", "ALLS", "ALLY", "ALMA", "ALME", "ALMS", "ALOE", "ALOW", "ALPS", "ALSO", "ALTO", "ALTS", "ALUM", "AMAH", "AMAS", "AMBO", "AMEN", "AMIA", "AMID", "AMIE", "AMIN", "AMIR", "AMIS", "AMMO", "AMOK", "AMPS", "AMUS", "AMYL", "ANAS", "ANDS", "ANES", "ANEW", "ANGA", "ANIL", "ANIS", "ANKH", "ANNA", "ANOA", "ANON", "ANSA", "ANTA", "ANTE", "ANTI", "ANTS", "APED", "APER", "APES", "APEX", "APOD", "APOS", "APPS", "APSE", "AQUA", "ARAK", "ARBS", "ARCH", "ARCO", "ARCS", "AREA", "ARES", "ARFS", "ARIA", "ARID", "ARIL", "ARKS", "ARMS", "ARMY", "ARTS", "ARTY", "ARUM", "ARVO", "ARYL", "ASCI", "ASEA", "ASHY", "ASKS", "ASPS", "ATAP", "ATES", "ATMA", "ATOM", "ATOP", "AUKS", "AULD", "AUNT", "AURA", "AUTO", "AVER", "AVES", "AVID", "AVOS", "AVOW", "AWAY", "AWED", "AWEE", "AWES", "AWLS", "AWNS", "AWNY", "AWOL", "AWRY", "AXAL", "AXED", "AXEL", "AXES", "AXIL", "AXIS", "AXLE", "AXON", "AYAH", "AYES", "AYIN", "AZAN", "AZON",
    "BAAL", "BAAS", "BABA", "BABE", "BABU", "BABY", "BACH", "BACK", "BADE", "BADS", "BAFF", "BAGS", "BAHT", "BAIL", "BAIT", "BAKE", "BALD", "BALE", "BALK", "BALL", "BALM", "BALS", "BAMS", "BAND", "BANE", "BANG", "BANI", "BANK", "BANS", "BAPS", "BARB", "BARD", "BARE", "BARF", "BARK", "BARM", "BARN", "BARS", "BASE", "BASH", "BASK", "BASS", "BAST", "BATE", "BATH", "BATS", "BATT", "BAUD", "BAWD", "BAWL", "BAYS", "BEAD", "BEAK", "BEAM", "BEAN", "BEAR", "BEAT", "BEAU", "BECK", "BEDS", "BEDU", "BEEF", "BEEN", "BEEP", "BEER", "BEES", "BEET", "BEGS", "BELL", "BELS", "BELT", "BEMA", "BEND", "BENE", "BENS", "BENT", "BERG", "BERK", "BERM", "BEST", "BETA", "BETH", "BETS", "BEVY", "BEYS", "BHUT", "BIAS", "BIBB", "BIBS", "BICE", "BIDE", "BIDI", "BIDS", "BIER", "BIFF", "BIGS", "BIKE", "BILE", "BILK", "BILL", "BIMA", "BIND", "BINE", "BINS", "BINT", "BIOG", "BIOS", "BIRD", "BIRK", "BIRL", "BIRO", "BIRR", "BISE", "BISK", "BITE", "BITS", "BITT", "BIZE", "BLAB", "BLAE", "BLAH", "BLAM", "BLAT", "BLAW", "BLEB", "BLED", "BLET", "BLEW", "BLIN", "BLIP", "BLOB", "BLOC", "BLOG", "BLOT", "BLOW", "BLUB", "BLUE", "BLUR", "BOAR", "BOAS", "BOAT", "BOBS", "BOCK", "BODE", "BODS", "BODY", "BOFF", "BOGS", "BOGY", "BOHO", "BOIL", "BOLA", "BOLD", "BOLE", "BOLL", "BOLO", "BOLT", "BOMB", "BOND", "BONE", "BONG", "BONK", "BONY", "BOOB", "BOOK", "BOOM", "BOON", "BOOR", "BOOS", "BOOT", "BOPS", "BORA", "BORD", "BORE", "BORK", "BORN", "BORT", "BOSH", "BOSK", "BOSS", "BOTA", "BOTH", "BOTS", "BOTT", "BOUT", "BOWL", "BOWS", "BOXY", "BOYO", "BOYS", "BOZO", "BRAD", "BRAE", "BRAG", "BRAN", "BRAS", "BRAT", "BRAW", "BRAY", "BRED", "BREE", "BREN", "BREW", "BRIE", "BRIG", "BRIM", "BRIN", "BRIO", "BRIS", "BRIT", "BROO", "BROS", "BROW", "BRRR", "BRUT", "BRUX", "BUBO", "BUBS", "BUBU", "BUCK", "BUDS", "BUFF", "BUGS", "BUHL", "BUHR", "BULB", "BULK", "BULL", "BUMF", "BUMP", "BUMS", "BUNA", "BUND", "BUNG", "BUNK", "BUNN", "BUNS", "BUNT", "BUOY", "BURA", "BURB", "BURD", "BURG", "BURL", "BURN", "BURP", "BURR", "BURS", "BURY", "BUSH", "BUSK", "BUSS", "BUST", "BUSY", "BUTE", "BUTS", "BUTT", "BUYS", "BUZZ", "BYES", "BYRE", "BYRL", "BYTE",
    "CABS", "CACA", "CADE", "CADI", "CADS", "CAFE", "CAFF", "CAGE", "CAGY", "CAID", "CAIN", "CAKE", "CAKY", "CALF", "CALK", "CALL", "CALM", "CALO", "CALX", "CAME", "CAMI", "CAMO", "CAMP", "CAMS", "CANE", "CANS", "CANT", "CAPE", "CAPH", "CAPI", "CAPO", "CAPS", "CARB", "CARD", "CARE", "CARK", "CARL", "CARN", "CARP", "CARR", "CARS", "CART", "CASA", "CASE", "CASH", "CASK", "CAST", "CATE", "CATS", "CAUL", "CAVE", "CAVY", "CAWS", "CAYS", "CECA", "CEDE", "CEDI", "CEES", "CEIL", "CELL", "CELS", "CELT", "CENT", "CEPE", "CEPS", "CERE", "CERO", "CESS", "CETE", "CHAD", "CHAI", "CHAM", "CHAO", "CHAP", "CHAR", "CHAT", "CHAV", "CHAW", "CHEF", "CHEM", "CHER", "CHEW", "CHEZ", "CHIA", "CHIB", "CHIC", "CHID", "CHIK", "CHIN", "CHIP", "CHIS", "CHIT", "CHIV", "CHIZ", "CHOC", "CHOG", "CHON", "CHOP", "CHOU", "CHOW", "CHUB", "CHUG", "CHUM", "CHUR", "CHUT", "CIAO", "CIGS", "CILL", "CINE", "CINQ", "CION", "CIRE", "CIRL", "CIST", "CITE", "CITS", "CITY", "CIVE", "CLAD", "CLAG", "CLAM", "CLAN", "CLAP", "CLAT", "CLAW", "CLAY", "CLEF", "CLEG", "CLEM", "CLEW", "CLIP", "CLIT", "CLOD", "CLOG", "CLON", "CLOP", "CLOT", "CLOU", "CLOW", "CLOY", "CLUB", "CLUE", "COAL", "COAT", "COAX", "COBB", "COBS", "COCA", "COCH", "COCK", "COCO", "CODA", "CODE", "CODS", "COED", "COFF", "COFT", "COGS", "COHO", "COIF", "COIL", "COIN", "COIR", "COIT", "COKE", "COKY", "COLA", "COLD", "COLE", "COLL", "COLS", "COLT", "COLY", "COMA", "COMB", "COME", "COMM", "COMP", "COMS", "COND", "CONE", "CONF", "CONI", "CONK", "CONN", "CONS", "CONY", "COOF", "COOK", "COOL", "COOM", "COON", "COOP", "COOS", "COOT", "COPE", "COPI", "COPS", "COPY", "CORD", "CORE", "CORF", "CORK", "CORM", "CORN", "CORS", "CORY", "COSE", "COSH", "COSS", "COST", "COSY", "COTE", "COTH", "COTS", "COTT", "COUP", "COUR", "COVE", "COWK", "COWL", "COWP", "COWS", "COWY", "COXA", "COXY", "COYS", "COZE", "COZY", "CRAB", "CRAG", "CRAM", "CRAN", "CRAP", "CRAS", "CRAW", "CRAY", "CRED", "CREE", "CREM", "CREW", "CRIA", "CRIB", "CRIM", "CRIS", "CRIT", "CROC", "CROG", "CRON", "CROP", "CROW", "CRUD", "CRUE", "CRUS", "CRUX", "CUBE", "CUBS", "CUCK", "CUDS", "CUED", "CUES", "CUFF", "CUIF", "CUIT", "CUKE", "CULL", "CULM", "CULT", "CUPS", "CURB", "CURD", "CURE", "CURF", "CURL", "CURN", "CURR", "CURS", "CURT", "CUSH", "CUSK", "CUSP", "CUSS", "CUTE", "CUTS", "CWMS", "CYAN", "CYMA", "CYME", "CYST", "CYTE", "CZAR",
    "DABS", "DACE", "DADA", "DADO", "DADS", "DAFF", "DAFT", "DAGS", "DAHL", "DAHS", "DAIS", "DAKS", "DALE", "DALS", "DAME", "DAMP", "DAMS", "DANG", "DANK", "DANS", "DAPS", "DARB", "DARE", "DARK", "DARN", "DART", "DASH", "DATA", "DATE", "DATO", "DAUB", "DAUT", "DAVY", "DAWK", "DAWN", "DAWS", "DAWT", "DAYS", "DAZE", "DEAD", "DEAF", "DEAL", "DEAN", "DEAR", "DEBS", "DEBT", "DECK", "DECO", "DEED", "DEEM", "DEEP", "DEER", "DEES", "DEET", "DEFI", "DEFT", "DEFY", "DEIL", "DEKE", "DELE", "DELF", "DELI", "DELL", "DELS", "DELT", "DEME", "DEMO", "DEMY", "DENE", "DENI", "DENS", "DENT", "DENY", "DERE", "DERM", "DESK", "DEVA", "DEVS", "DEWS", "DEWY", "DEXY", "DEYS", "DHAK", "DHAL", "DHOW", "DIAL", "DIBS", "DICE", "DIDO", "DIDY", "DIED", "DIEL", "DIES", "DIET", "DIFF", "DIFS", "DIGS", "DILL", "DIME", "DIMS", "DINE", "DING", "DINO", "DINS", "DINT", "DIOL", "DIPS", "DIPT", "DIRE", "DIRK", "DIRL", "DIRT", "DISC", "DISH", "DISK", "DISS", "DITA", "DITE", "DITS", "DITZ", "DIVA", "DIVE", "DJIN", "DOAT", "DOBY", "DOCK", "DOCS", "DODO", "DOER", "DOES", "DOFF", "DOGE", "DOGS", "DOGY", "DOIT", "DOJO", "DOLE", "DOLL", "DOLS", "DOLT", "DOME", "DOMS", "DONA", "DONE", "DONG", "DONS", "DOOM", "DOOR", "DOPA", "DOPE", "DOPY", "DORE", "DORK", "DORM", "DORP", "DORR", "DORS", "DORY", "DOSE", "DOSS", "DOST", "DOTE", "DOTH", "DOTS", "DOTY", "DOUM", "DOUR", "DOUX", "DOVE", "DOWN", "DOWS", "DOXY", "DOZE", "DOZY", "DRAB", "DRAG", "DRAM", "DRAT", "DRAW", "DRAY", "DREE", "DREG", "DREK", "DREW", "DRIB", "DRIP", "DROP", "DRUB", "DRUG", "DRUM", "DRYS", "DUAD", "DUAL", "DUBS", "DUCE", "DUCI", "DUCK", "DUCT", "DUDE", "DUDS", "DUEL", "DUES", "DUET", "DUFF", "DUGS", "DUIT", "DUKE", "DULL", "DULY", "DUMA", "DUMB", "DUMP", "DUNE", "DUNG", "DUNK", "DUNS", "DUNT", "DUOS", "DUPE", "DUPS", "DURA", "DURE", "DURN", "DURO", "DURR", "DUSK", "DUST", "DUTY", "DYAD", "DYED", "DYER", "DYES", "DYNE",
    "EACH", "EARL", "EARN", "EARS", "EASE", "EAST", "EASY", "EATH", "EATS", "EAUX", "EAVE", "EBBS", "EBON", "ECHE", "ECHO", "ECHT", "ECRU", "ECUS", "EDDO", "EDDY", "EDGE", "EDGY", "EDHS", "EDIT", "EELS", "EELY", "EERY", "EFFS", "EFTS", "EGAD", "EGAL", "EGER", "EGGS", "EGGY", "EGIS", "EGOS", "EIDE", "EKED", "EKES", "ELAN", "ELDS", "ELHI", "ELKS", "ELLS", "ELMS", "ELMY", "ELSE", "EMES", "EMEU", "EMIC", "EMIR", "EMIT", "EMMY", "EMUS", "EMYD", "ENDS", "ENGS", "ENOL", "ENOW", "ENUF", "ENVY", "EONS", "EPEE", "EPHA", "EPIC", "EPOS", "ERAS", "ERGO", "ERGS", "ERNE", "ERNS", "EROS", "ERRS", "ERST", "ESES", "ESNE", "ESPY", "ETAS", "ETCH", "ETHS", "ETIC", "ETNA", "ETUI", "EURO", "EVEN", "EVER", "EVES", "EVIL", "EWER", "EWES", "EXAM", "EXEC", "EXED", "EXES", "EXIT", "EXON", "EXPO", "EYAS", "EYED", "EYEN", "EYER", "EYES", "EYNE", "EYRA", "EYRE", "EYRY",
    "FABS", "FACE", "FACT", "FADE", "FADO", "FADS", "FAGS", "FAIL", "FAIN", "FAIR", "FAKE", "FALL", "FALX", "FAME", "FANE", "FANG", "FANO", "FANS", "FARD", "FARE", "FARL", "FARM", "FARO", "FASH", "FAST", "FATE", "FATS", "FAUN", "FAUX", "FAVA", "FAVE", "FAWN", "FAYS", "FAZE", "FEAL", "FEAR", "FEAT", "FECK", "FEDS", "FEEB", "FEED", "FEEL", "FEES", "FEET", "FEHS", "FELL", "FELT", "FEME", "FEMS", "FEND", "FENS", "FEOD", "FERE", "FERN", "FESS", "FEST", "FETA", "FETE", "FETS", "FEUD", "FEUS", "FIAR", "FIAT", "FIBS", "FICE", "FICO", "FIDO", "FIDS", "FIEF", "FIFE", "FIGS", "FILA", "FILE", "FILL", "FILM", "FILO", "FILS", "FIND", "FINE", "FINK", "FINO", "FINS", "FIRE", "FIRM", "FIRN", "FIRS", "FISC", "FISH", "FIST", "FITS", "FIVE", "FIXT", "FIZZ", "FLAB", "FLAG", "FLAK", "FLAM", "FLAN", "FLAP", "FLAT", "FLAW", "FLAX", "FLAY", "FLEA", "FLED", "FLEE", "FLEW", "FLEX", "FLEY", "FLIC", "FLIM", "FLIP", "FLIR", "FLIT", "FLOC", "FLOE", "FLOG", "FLOP", "FLOW", "FLUB", "FLUE", "FLUS", "FLUX", "FOAL", "FOAM", "FOBS", "FOCI", "FOES", "FOGS", "FOGY", "FOHN", "FOIL", "FOIN", "FOLD", "FOLK", "FOND", "FONS", "FONT", "FOOD", "FOOL", "FOOT", "FOPS", "FORA", "FORB", "FORD", "FORE", "FORK", "FORM", "FORT", "FOSS", "FOUL", "FOUR", "FOWL", "FOXY", "FOYS", "FOZY", "FRAE", "FRAG", "FRAP", "FRAT", "FRAY", "FREE", "FRET", "FRIG", "FRIT", "FRIZ", "FROE", "FROG", "FROM", "FROW", "FRUG", "FUBS", "FUCI", "FUDS", "FUEL", "FUGS", "FUGU", "FUJI", "FULL", "FUME", "FUMY", "FUND", "FUNK", "FUNS", "FURL", "FURS", "FURY", "FUSE", "FUSS", "FUTZ", "FUZE", "FUZZ", "FYCE", "FYKE",
    "GABS", "GABY", "GADI", "GADS", "GAED", "GAEN", "GAES", "GAFF", "GAGA", "GAGE", "GAGS", "GAIN", "GAIT", "GALA", "GALE", "GALL", "GALS", "GAMA", "GAMB", "GAME", "GAMP", "GAMS", "GAMY", "GANE", "GANG", "GAOL", "GAPE", "GAPS", "GAPY", "GARB", "GARS", "GASH", "GASP", "GAST", "GATE", "GATS", "GAUD", "GAUM", "GAUN", "GAUR", "GAVE", "GAWK", "GAWP", "GAYS", "GAZE", "GEAR", "GECK", "GEDS", "GEED", "GEEK", "GEES", "GEEZ", "GELD", "GELS", "GELT", "GEMS", "GENE", "GENS", "GENT", "GENU", "GERM", "GEST", "GETA", "GETS", "GEUM", "GHAT", "GHEE", "GHIS", "GIBE", "GIBS", "GIDS", "GIED", "GIEN", "GIES", "GIFT", "GIGA", "GIGS", "GILD", "GILL", "GILT", "GIMP", "GINK", "GINS", "GIPS", "GIRD", "GIRL", "GIRN", "GIRO", "GIRT", "GIST", "GITE", "GITS", "GIVE", "GLAD", "GLAM", "GLED", "GLEE", "GLEG", "GLEN", "GLEY", "GLIA", "GLIB", "GLIM", "GLOB", "GLOM", "GLOP", "GLOW", "GLUE", "GLUG", "GLUM", "GLUT", "GNAR", "GNAT", "GNAW", "GNUS", "GOAD", "GOAL", "GOAS", "GOAT", "GOBO", "GOBS", "GOBY", "GODS", "GOER", "GOES", "GOGO", "GOLD", "GOLF", "GONE", "GONG", "GOOD", "GOOF", "GOON", "GOOP", "GOOS", "GORE", "GORM", "GORP", "GORY", "GOSH", "GOTH", "GOUT", "GOWD", "GOWK", "GOWN", "GOYS", "GRAB", "GRAD", "GRAM", "GRAN", "GRAT", "GRAY", "GREE", "GREW", "GREY", "GRID", "GRIG", "GRIM", "GRIN", "GRIP", "GRIT", "GROG", "GROK", "GROT", "GROW", "GRUB", "GRUE", "GRUM", "GUAN", "GAUR", "GUCK", "GUDE", "GUFF", "GULF", "GULL", "GULP", "GULS", "GUMS", "GUNK", "GUNS", "GURU", "GUSH", "GUST", "GUTS", "GUVS", "GUYS", "GYBE", "GYMS", "GYPS", "GYRE", "GYRI", "GYRO", "GYVE",
    "HAAF", "HAAR", "HABU", "HACK", "HADE", "HADJ", "HAGS", "HAHA", "HAHS", "HAIK", "HAIL", "HAIR", "HAJI", "HAJJ", "HAKE", "HAKU", "HALE", "HALF", "HALL", "HALM", "HALO", "HALT", "HAME", "HAMS", "HAND", "HANG", "HANK", "HANT", "HAPS", "HARD", "HARE", "HARK", "HARL", "HARM", "HARP", "HART", "HASH", "HASP", "HAST", "HATE", "HATH", "HATS", "HAUL", "HAUT", "HAVE", "HAWK", "HAWS", "HAYS", "HAZE", "HAZY", "HEAD", "HEAL", "HEAP", "HEAR", "HEAT", "HEBE", "HECK", "HEED", "HEEL", "HEFT", "HEHS", "HEIL", "HEIR", "HELD", "HELL", "HELM", "HELO", "HELP", "HEME", "HEMP", "HEMS", "HENS", "HENT", "HERB", "HERD", "HERE", "HERL", "HERM", "HERN", "HERO", "HERS", "HEST", "HETH", "HETS", "HEWN", "HEWS", "HICK", "HIDE", "HIED", "HIES", "HIGH", "HIKE", "HILA", "HILI", "HILL", "HILT", "HIMS", "HIND", "HINS", "HINT", "HIPS", "HIRE", "HISN", "HISS", "HIST", "HITS", "HIVE", "HOAR", "HOAX", "HOBO", "HOBS", "HOCK", "HODS", "HOED", "HOER", "HOES", "HOGG", "HOGS", "HOKE", "HOLD", "HOLK", "HOLM", "HOLP", "HOLS", "HOLT", "HOLY", "HOME", "HOMY", "HONE", "HONG", "HONS", "HOOD", "HOOF", "HOOK", "HOOP", "HOOT", "HOPE", "HOPS", "HORA", "HORN", "HOSE", "HOST", "HOTS", "HOUR", "HOVE", "HOWE", "HOWL", "HOWS", "HOYA", "HOYS", "HUBS", "HUCK", "HUED", "HUES", "HUFF", "HUGE", "HUGS", "HUIC", "HULA", "HULK", "HULL", "HUMP", "HUMS", "HUNG", "HUNH", "HUNK", "HUNS", "HUNT", "HURL", "HURT", "HUSH", "HUSK", "HUTS", "HWAN", "HYLA", "HYMN", "HYPE", "HYPO", "HYPS", "HYTE",
    "IAMB", "IBEX", "IBIS", "ICED", "ICES", "ICHS", "ICKY", "ICON", "IDEA", "IDEM", "IDES", "IDLE", "IDLY", "IDOL", "IDYL", "IFFY", "IGGS", "IGLU", "IKAT", "IKON", "ILEA", "ILEX", "ILIA", "ILKA", "ILKS", "ILLS", "ILLY", "IMAM", "IMID", "IMMY", "IMPI", "IMPS", "INBY", "INCH", "INFO", "INIA", "INKS", "INKY", "INLY", "INNS", "INRO", "INTI", "INTO", "IONS", "IOTA", "IRED", "IRES", "IRID", "IRIS", "IRKS", "IRON", "ISBA", "ISLE", "ISMS", "ITCH", "ITEM", "IWIS", "IXIA", "IZAR",
    "JABS", "JACK", "JADE", "JAGG", "JAGS", "JAIL", "JAKE", "JAMB", "JAMS", "JANE", "JAPE", "JARL", "JARS", "JATO", "JAUK", "JAUP", "JAVA", "JAWS", "JAYS", "JAZZ", "JEAN", "JEED", "JEEP", "JEER", "JEES", "JEEZ", "JEFE", "JEHU", "JELL", "JEON", "JERK", "JESS", "JEST", "JETE", "JETS", "JEUX", "JEWS", "JIAO", "JIBB", "JIBE", "JIBS", "JIFF", "JIGS", "JILL", "JILT", "JIMP", "JINK", "JINN", "JINS", "JINX", "JISM", "JIVE", "JIVY", "JOBS", "JOCK", "JOES", "JOEY", "JOGS", "JOHN", "JOIN", "JOKE", "JOKY", "JOLE", "JOLT", "JOSH", "JOSS", "JOTA", "JOTS", "JOUK", "JOWL", "JOWS", "JOYS", "JUBA", "JUBE", "JUCO", "JUDO", "JUGS", "JUJU", "JUKE", "JUKU", "JUMP", "JUNK", "JUPE", "JURA", "JURY", "JUST", "JUTE", "JUTS",
    "KAAS", "KABS", "KADI", "KAES", "KAFS", "KAGU", "KAIF", "KAIL", "KAIN", "KAKA", "KAKI", "KALE", "KAME", "KAMI", "KANA", "KANE", "KAON", "KAPA", "KAPH", "KARN", "KART", "KATA", "KATS", "KAVA", "KAYO", "KAYS", "KBAR", "KEAS", "KECK", "KEEF", "KEEK", "KEEL", "KEEN", "KEEP", "KEET", "KEFS", "KEGS", "KEIR", "KELP", "KELT", "KEMP", "KENO", "KENS", "KENT", "KEPI", "KEPS", "KEPT", "KERB", "KERF", "KERN", "KETO", "KEYS", "KHAF", "KHAN", "KHAT", "KHET", "KHIS", "KIBE", "KICK", "KIDS", "KIEF", "KIER", "KIFS", "KILL", "KILN", "KILO", "KILT", "KINA", "KIND", "KINE", "KING", "KINK", "KINO", "KINS", "KIPS", "KIRK", "KIRN", "KIRS", "KISS", "KIST", "KITE", "KITH", "KITS", "KIVA", "KIWI", "KLIK", "KNAP", "KNAR", "KNEE", "KNEW", "KNIT", "KNOB", "KNOP", "KNOT", "KNOW", "KNUR", "KOAN", "KOAS", "KOBO", "KOBS", "KOEL", "KOHL", "KOIS", "KOJI", "KOLA", "KOLO", "KONK", "KOOK", "KOPH", "KOPS", "KORA", "KORE", "KORS", "KOSS", "KOTO", "KRIS", "KUDO", "KUDU", "KUES", "KUFI", "KUNA", "KUNE", "KURU", "KVAS", "KYAK", "KYAR", "KYAT", "KYES", "KYTE",
    "LABS", "LACE", "LACK", "LACS", "LACY", "LADE", "LADS", "LADY", "LAGS", "LAIC", "LAID", "LAIN", "LAIR", "LAKE", "LAKH", "LAKY", "LALL", "LAMA", "LAMB", "LAME", "LAMP", "LAMS", "LAND", "LANE", "LANG", "LANK", "LAPS", "LARD", "LARI", "LARK", "LARS", "LASE", "LASH", "LASS", "LAST", "LATE", "LATH", "LATI", "LATS", "LATU", "LAUD", "LAVA", "LAVE", "LAVS", "LAWN", "LAWS", "LAYS", "LAZE", "LAZY", "LEAD", "LEAF", "LEAK", "LEAL", "LEAN", "LEAP", "LEAR", "LEAS", "LECH", "LEEK", "LEER", "LEES", "LEET", "LEFT", "LEGS", "LEHR", "LEIS", "LEKE", "LEKS", "LEKU", "LEND", "LENO", "LENS", "LENT", "LEPT", "LESS", "LEST", "LETS", "LEUD", "LEVA", "LEVE", "LEVO", "LEVS", "LEVY", "LEWD", "LEYS", "LIAR", "LIBS", "LICE", "LICH", "LICK", "LIDO", "LIDS", "LIED", "LIEF", "LIEN", "LIER", "LIES", "LIEU", "LIFE", "LIFT", "LIKE", "LILL", "LILO", "LILT", "LILY", "LIMA", "LIMB", "LIME", "LIMN", "LIMO", "LIMP", "LIMY", "LINE", "LING", "LINK", "LINN", "LINO", "LINS", "LINT", "LINY", "LION", "LIPA", "LIPE", "LIPS", "LIRA", "LIRI", "LISP", "LIST", "LITE", "LITS", "LITU", "LIVE", "LOAD", "LOAF", "LOAM", "LOAN", "LOBE", "LOBI", "LOBO", "LOBS", "LOCA", "LOCH", "LOCI", "LOCK", "LOCO", "LODE", "LOFT", "LOGE", "LOGO", "LOGS", "LOGY", "LOID", "LOIN", "LOLL", "LONE", "LONG", "LOOF", "LOOK", "LOOM", "LOON", "LOOP", "LOOS", "LOOT", "LOPE", "LOPS", "LORD", "LORE", "LORN", "LORY", "LOSE", "LOSH", "LOSS", "LOST", "LOTA", "LOTH", "LOTI", "LOTS", "LOUD", "LOUN", "LOUP", "LOUR", "LOUS", "LOUT", "LOVE", "LOWE", "LOWN", "LOWS", "LOWT", "LUAU", "LUBE", "LUCE", "LUCK", "LUDE", "LUES", "LUFF", "LUGE", "LUGS", "LULL", "LULU", "LUMA", "LUMP", "LUMS", "LUNA", "LUNE", "LUNG", "LUNK", "LUNT", "LUNY", "LURE", "LURK", "LUSH", "LUST", "LUTE", "LUTZ", "LUVS", "LUXE", "LWEI", "LYCH", "LYES", "LYNX", "LYRA", "LYRE", "LYSE",
    "MAAR", "MABE", "MACE", "MACH", "MACK", "MACS", "MADE", "MADS", "MAES", "MAGE", "MAGI", "MAGS", "MAID", "MAIL", "MAIM", "MAIN", "MAIR", "MAKE", "MAKO", "MALE", "MALL", "MALM", "MALT", "MAMA", "MANA", "MANE", "MANO", "MANS", "MANY", "MAPS", "MARA", "MARC", "MARE", "MARK", "MARL", "MARS", "MART", "MASA", "MASH", "MASK", "MASS", "MAST", "MATE", "MATH", "MATS", "MATT", "MAUD", "MAUL", "MAUN", "MAUT", "MAWN", "MAWS", "MAXI", "MAYA", "MAYO", "MAYS", "MAZE", "MAZY", "MEAD", "MEAL", "MEAN", "MEAT", "MEDS", "MEED", "MEEK", "MEET", "MEGA", "MEGS", "MELD", "MELL", "MELS", "MELT", "MEME", "MEMO", "MEMS", "MEND", "MENO", "MENU", "MEOU", "MEOW", "MERC", "MERE", "MERK", "MERL", "MESA", "MESH", "MESS", "META", "METE", "METH", "METS", "MEWL", "MEWS", "MEZE", "MHOS", "MIBS", "MICA", "MICE", "MICS", "MIDI", "MIDS", "MIEN", "MIFF", "MIGS", "MIKE", "MILD", "MILE", "MILK", "MILL", "MILO", "MILS", "MILT", "MIME", "MINA", "MIND", "MINE", "MINI", "MINK", "MINT", "MINX", "MIPS", "MIRE", "MIRI", "MIRK", "MIRS", "MIRY", "MISE", "MISO", "MISS", "MIST", "MITE", "MITT", "MITY", "MIXT", "MIZZ", "MNAS", "MOAI", "MOAN", "MOAS", "MOAT", "MOBE", "MOBS", "MOBY", "MOCK", "MOCS", "MODE", "MODI", "MODS", "MOGS", "MOHO", "MOIL", "MOJO", "MOKE", "MOLA", "MOLD", "MOLE", "MOLL", "MOLS", "MOLT", "MOLY", "MOME", "MOMI", "MOMS", "MONA", "MONK", "MONO", "MONS", "MONY", "MOOD", "MOOL", "MOON", "MOOR", "MOOS", "MOOT", "MOPE", "MOPS", "MOPY", "MORA", "MORE", "MORN", "MORS", "MORT", "MOSE", "MOSH", "MOSK", "MOSS", "MOST", "MOTE", "MOTH", "MOTS", "MOTT", "MOTU", "MOUE", "MOVE", "MOWN", "MOWS", "MOXA", "MOYA", "MOYS", "MOZE", "MOZO", "MOZZ", "MPOX", "MUCH", "MUCK", "MUDS", "MUFF", "MUGS", "MUID", "MUIR", "MULE", "MULL", "MUMM", "MUMP", "MUMS", "MUNI", "MUNS", "MUON", "MURA", "MURE", "MURK", "MURL", "MURR", "MUSE", "MUSH", "MUSK", "MUSS", "MUST", "MUTE", "MUTS", "MUTT", "MUZZ", "MWAH", "MYNA", "MYTH",
    "NAAN", "NABE", "NABS", "NADA", "NAFF", "NAGS", "NAIF", "NAIL", "NALA", "NAME", "NANA", "NANS", "NAOI", "NAOS", "NAPA", "NAPE", "NAPS", "NARC", "NARD", "NARK", "NARY", "NAVE", "NAVY", "NAYS", "NAZI", "NEAP", "NEAR", "NEAT", "NEBS", "NECK", "NEED", "NEEM", "NEEP", "NEGS", "NEIF", "NEMA", "NENE", "NEON", "NERD", "NESS", "NEST", "NETS", "NETT", "NEUK", "NEUM", "NEVE", "NEVI", "NEWS", "NEWT", "NEXT", "NIBS", "NICE", "NICK", "NIDE", "NIDI", "NIGH", "NILL", "NILS", "NIMS", "NINE", "NIPA", "NIPS", "NISI", "NITE", "NITS", "NIXE", "NIXY", "NOBS", "NOCK", "NODE", "NODS", "NOEL", "NOES", "NOGG", "NOGS", "NOIL", "NOIR", "NOLO", "NOMA", "NOME", "NOMS", "NONA", "NONE", "NOOK", "NOON", "NOPE", "NORI", "NORM", "NOSE", "NOSH", "NOSY", "NOTA", "NOTE", "NOUN", "NOUS", "NOVA", "NOWS", "NOWT", "NUBS", "NUDE", "NUKE", "NULL", "NUMB", "NUNS", "NURD", "NURL", "NUTS",
    "OAFS", "OAKS", "OAKY", "OARS", "OAST", "OATH", "OATS", "OBAS", "OBES", "OBEY", "OBIA", "OBIS", "OBIT", "OBOE", "OBOL", "OCAS", "ODAH", "ODAS", "ODDS", "ODEA", "ODES", "ODIC", "ODOR", "ODYL", "OFAY", "OFFS", "OGAM", "OGEE", "OGLE", "OGRE", "OHED", "OHIA", "OHMS", "OILS", "OILY", "OINK", "OKAS", "OKAY", "OKEH", "OKES", "OKRA", "OLDS", "OLDY", "OLEA", "OLEO", "OLES", "OLIO", "OLLA", "OMEN", "OMER", "OMIT", "ONCE", "ONES", "ONLY", "ONOS", "ONTO", "ONUS", "ONYX", "OOHS", "OOPS", "OOTS", "OOZE", "OOZY", "OPAH", "OPAL", "OPED", "OPEN", "OPES", "OPTS", "OPUS", "ORAD", "ORAL", "ORBS", "ORBY", "ORCA", "ORCS", "ORDO", "ORES", "ORGY", "ORLE", "ORRA", "ORTS", "ORYX", "ORZO", "OSAR", "OSES", "OSSA", "OTIC", "OTTO", "OUCH", "OUDS", "OUPH", "OURS", "OUST", "OUTS", "OUZO", "OVAL", "OVEN", "OVER", "OVUM", "OWED", "OWES", "OWLS", "OWNS", "OWSE", "OXEN", "OXES", "OXID", "OXIM", "OYER", "OYES", "OYEZ",
    "PACA", "PACE", "PACK", "PACS", "PACT", "PACY", "PADI", "PADS", "PAGE", "PAID", "PAIK", "PAIL", "PAIN", "PAIR", "PAIS", "PAKS", "PALE", "PALI", "PALL", "PALM", "PALP", "PALS", "PALY", "PAMS", "PANE", "PANG", "PANS", "PANT", "PAPA", "PAPE", "PAPS", "PARA", "PARD", "PARE", "PARK", "PARR", "PARS", "PART", "PASE", "PASH", "PASS", "PAST", "PATE", "PATH", "PATS", "PATY", "PAUA", "PAUL", "PAVE", "PAWS", "PAYS", "PEAG", "PEAK", "PEAL", "PEAN", "PEAR", "PEAS", "PEAT", "PECH", "PECK", "PECS", "PEDS", "PEED", "PEEK", "PEEL", "PEEN", "PEEP", "PEER", "PEES", "PEGS", "PEHS", "PEIN", "PEKE", "PELE", "PELF", "PELL", "PELS", "PELT", "PEND", "PENE", "PENG", "PENI", "PENK", "PENS", "PENT", "PEON", "PEPO", "PEPS", "PERC", "PERE", "PERI", "PERK", "PERM", "PERN", "PERP", "PERT", "PERV", "PESO", "PEST", "PETS", "PEWS", "PFFT", "PFUI", "PHAT", "PHEW", "PHIS", "PHIZ", "PHON", "PHOT", "PHUT", "PIAL", "PIAN", "PIAS", "PICA", "PICE", "PICK", "PICS", "PIED", "PIER", "PIES", "PIGS", "PIKA", "PIKE", "PIKI", "PILE", "PILI", "PILL", "PILY", "PIMA", "PIMP", "PINA", "PINE", "PING", "PINK", "PINS", "PINT", "PINY", "PION", "PIPE", "PIPS", "PIPY", "PIRN", "PISH", "PISO", "PISS", "PITA", "PITH", "PITS", "PITY", "PIXY", "PLAN", "PLAP", "PLAT", "PLAY", "PLEA", "PLEB", "PLED", "PLEW", "PLEX", "PLIE", "PLOD", "PLOP", "PLOT", "PLOW", "PLOY", "PLUG", "PLUM", "PLUS", "POCK", "POCO", "PODS", "POEM", "POET", "POGY", "POHS", "POIS", "POKE", "POKY", "POLE", "POLK", "POLL", "POLO", "POLS", "POLT", "POLY", "POME", "POMO", "POMP", "POMS", "POND", "PONE", "PONG", "PONK", "PONS", "PONY", "POOD", "POOF", "POOH", "POOL", "POON", "POOP", "POOR", "POOS", "POOT", "POPE", "POPS", "PORE", "PORK", "PORN", "PORT", "PORY", "POSE", "POSH", "POSS", "POST", "POSY", "POTS", "POUF", "POUR", "POUT", "POWS", "POXY", "POZZ", "PRAM", "PRAO", "PRAT", "PRAU", "PRAY", "PREE", "PREP", "PREY", "PREZ", "PRIG", "PRIM", "PROA", "PROB", "PROD", "PROF", "PROG", "PROM", "PROP", "PROS", "PROW", "PSIS", "PSST", "PTUI", "PUBS", "PUCE", "PUCK", "PUDS", "PUFF", "PUGS", "PUKE", "PULA", "PULE", "PULI", "PULK", "PULL", "PULP", "PULS", "PULU", "PULY", "PUMA", "PUMP", "PUNA", "PUNG", "PUNK", "PUNS", "PUNT", "PUNY", "PUPA", "PUPS", "PUPU", "PURE", "PURI", "PURL", "PURR", "PURS", "PUSH", "PUSS", "PUTS", "PUTT", "PUTZ", "PYAS", "PYES", "PYIC", "PYIN", "PYRE", "PYRO",
    "QADI", "QAID", "QATS", "QOPH", "QUAD", "QUAG", "QUAI", "QUAT", "QUAY", "QUEY", "QUID", "QUIN", "QUIP", "QUIT", "QUIZ", "QUOD",
    "RABI", "RACA", "RACE", "RACH", "RACK", "RACY", "RADS", "RAFF", "RAFT", "RAGA", "RAGE", "RAGG", "RAGS", "RAGU", "RAIA", "RAID", "RAIK", "RAIL", "RAIN", "RAIS", "RAIT", "RAJA", "RAKE", "RAKI", "RAKU", "RALE", "RAMI", "RAMP", "RAMS", "RAND", "RANG", "RANI", "RANK", "RANT", "RAPE", "RAPS", "RAPT", "RARE", "RASE", "RASH", "RASP", "RAST", "RATA", "RATE", "RATH", "RATO", "RATS", "RAVE", "RAWS", "RAYA", "RAYS", "RAZE", "RAZZ", "READ", "REAL", "REAM", "REAP", "REAR", "REBS", "RECK", "RECS", "REDD", "REDE", "REDO", "REDS", "REED", "REEF", "REEK", "REEL", "REES", "REFS", "REFT", "REGS", "REIF", "REIN", "REIS", "REKE", "RELY", "REMS", "REND", "RENT", "REPO", "REPP", "REPS", "RESH", "REST", "RETE", "RETS", "REVS", "RHEA", "RHOS", "RHUS", "RIAD", "RIAL", "RIAS", "RIBS", "RICE", "RICH", "RICK", "RIDS", "RIEL", "RIFE", "RIFF", "RIFS", "RIFT", "RIGS", "RILE", "RILL", "RIMA", "RIME", "RIMS", "RIMY", "RIND", "RING", "RINK", "RINS", "RIOT", "RIPE", "RIPS", "RISE", "RISK", "RISP", "RITE", "RITS", "RITT", "RITZ", "RIVE", "ROAD", "ROAM", "ROAN", "ROAR", "ROBE", "ROBS", "ROCK", "ROCS", "RODE", "RODS", "ROES", "ROIL", "ROIN", "ROKE", "ROKS", "ROLE", "ROLF", "ROLL", "ROMA", "ROMP", "ROMS", "ROND", "RONE", "ROOF", "ROOK", "ROOM", "ROOS", "ROOT", "ROPE", "ROPY", "ROSE", "ROSY", "ROTA", "ROTE", "ROTI", "ROTS", "ROUE", "ROUL", "ROUM", "ROUP", "ROUT", "ROUX", "ROVE", "ROWS", "RUBE", "RUBS", "RUBY", "RUCK", "RUCS", "RUDD", "RUDE", "RUED", "RUER", "RUES", "RUFF", "RUGS", "RUIN", "RULE", "RULY", "RUMP", "RUNS", "RUNT", "RURP", "RUSH", "RUSK", "RUST", "RUTH", "RUTS", "RYAS", "RYES", "RYKE", "RYND", "RYOT", "RYPE",
    "SAAG", "SABE", "SABS", "SACK", "SACS", "SADE", "SADI", "SAFE", "SAGA", "SAGE", "SAGO", "SAGS", "SAGY", "SAID", "SAIL", "SAIM", "SAIN", "SAKE", "SAKI", "SALE", "SALL", "SALP", "SALS", "SALT", "SAMA", "SAME", "SAMP", "SAMS", "SAND", "SANE", "SANG", "SANK", "SANS", "SAPS", "SARD", "SARI", "SARK", "SASH", "SASS", "SATE", "SAUL", "SAVE", "SAWN", "SAWS", "SAYS", "SCAB", "SCAD", "SCAG", "SCAM", "SCAN", "SCAR", "SCAT", "SCOP", "SCOT", "SCOW", "SCRY", "SCUD", "SCUM", "SCUP", "SCUR", "SCUT", "SEAL", "SEAM", "SEAN", "SEAR", "SEAS", "SEAT", "SECS", "SECT", "SEED", "SEEK", "SEEL", "SEEM", "SEEN", "SEEP", "SEER", "SEES", "SEGO", "SEGS", "SEIF", "SEIS", "SEKT", "SELD", "SELL", "SELS", "SEME", "SEMI", "SEND", "SENE", "SENS", "SENT", "SEPS", "SEPT", "SERA", "SERE", "SERF", "SERS", "SESS", "SETA", "SETS", "SETT", "SEWN", "SEWS", "SEXT", "SEXY", "SHAD", "SHAG", "SHAH", "SHAM", "SHAW", "SHAY", "SHEA", "SHED", "SHES", "SHEW", "SHIM", "SHIN", "SHIP", "SHIR", "SHIV", "SHMO", "SHOD", "SHOE", "SHOG", "SHOO", "SHOP", "SHOT", "SHOW", "SHRI", "SHUL", "SHUN", "SHUT", "SIAL", "SIBB", "SIBS", "SICE", "SICK", "SICS", "SIDE", "SIFT", "SIGH", "SIGN", "SIKA", "SIKE", "SILD", "SILK", "SILL", "SILO", "SILT", "SIMA", "SIMP", "SIMS", "SIND", "SINE", "SING", "SINH", "SINK", "SINS", "SIPE", "SIPS", "SIRE", "SIRS", "SISS", "SIST", "SITE", "SITS", "SIZE", "SIZY", "SKAG", "SKAS", "SKAT", "SKEE", "SKEG", "SKEP", "SKEW", "SKID", "SKIM", "SKIN", "SKIP", "SKIS", "SKIT", "SKUA", "SLAB", "SLAG", "SLAM", "SLAP", "SLAT", "SLAW", "SLAY", "SLEB", "SLED", "SLEW", "SLID", "SLIM", "SLIP", "SLIT", "SLOB", "SLOE", "SLOG", "SLOP", "SLOT", "SLOW", "SLUB", "SLUE", "SLUG", "SLUM", "SLUR", "SMIT", "SMOG", "SMUG", "SMUT", "SNAB", "SNAG", "SNAP", "SNAR", "SNAW", "SNED", "SNIB", "SNIG", "SNIP", "SNIT", "SNOB", "SNOD", "SNOG", "SNOT", "SNOW", "SNUB", "SNUG", "SOAK", "SOAP", "SOAR", "SOBA", "SOBS", "SOCA", "SOCK", "SODA", "SODS", "SOFA", "SOFT", "SOIL", "SOJA", "SOKE", "SOLA", "SOLD", "SOLE", "SOLI", "SOLO", "SOLS", "SOMA", "SOME", "SOMS", "SONG", "SONS", "SOOK", "SOON", "SOOT", "SOPH", "SOPS", "SORA", "SORB", "SORD", "SORE", "SORI", "SORN", "SORT", "SOSS", "SOTH", "SOTS", "SOUK", "SOUL", "SOUP", "SOUR", "SOUS", "SOWN", "SOWS", "SOYA", "SOYS", "SPAE", "SPAG", "SPAM", "SPAN", "SPAR", "SPAS", "SPAT", "SPAW", "SPAY", "SPEC", "SPED", "SPEW", "SPIK", "SPIN",
    "SPIT", "SPIV", "SPOT", "SPRY", "SPUD", "SPUE", "SPUG", "SPUN", "SPUR", "SRIS", "STAB", "STAG", "STAR", "STAT", "STAW", "STAY", "STEM", "STEP", "STET", "STEW", "STEY", "STIR", "STOA", "STOB", "STOP", "STOT", "STOW", "STUB", "STUD", "STUM", "STUN", "STYE", "SUBA", "SUBS", "SUCH", "SUDS", "SUED", "SUER", "SUES", "SUET", "SUGH", "SUIT", "SULK", "SULU", "SUMO", "SUMP", "SUMS", "SUNG", "SUNK", "SUNN", "SUNS", "SUPE", "SUPS", "SUQS", "SURA", "SURE", "SURF", "SUSS", "SWAB", "SWAG", "SWAM", "SWAN", "SWAP", "SWAT", "SWAY", "SWIG", "SWIM", "SWOB", "SWOP", "SWOT", "SWUM", "SYBO", "SYCE", "SYKE", "SYLI", "SYNC", "SYNE", "SYPH",
    "TABS", "TABU", "TACE", "TACH", "TACK", "TACO", "TACT", "TADS", "TAEL", "TAGS", "TAHR", "TAIL", "TAIN", "TAKA", "TAKE", "TALA", "TALC", "TALE", "TALI", "TALK", "TALL", "TAME", "TAMP", "TAMS", "TANG", "TANK", "TANS", "TAOS", "TAPA", "TAPE", "TAPS", "TAPU", "TARA", "TARE", "TARN", "TARO", "TARP", "TARS", "TART", "TASK", "TASS", "TATE", "TATS", "TAUS", "TAUT", "TAVS", "TAWS", "TAXA", "TAXI", "TAYS", "TEAK", "TEAL", "TEAM", "TEAR", "TEAS", "TEAT", "TECH", "TECS", "TEDS", "TEED", "TEEL", "TEEM", "TEEN", "TEES", "TEFF", "TEGS", "TELA", "TELE", "TELL", "TELS", "TELT", "TEMP", "TEND", "TENS", "TENT", "TEPA", "TERM", "TERN", "TEST", "TETH", "TETS", "TEWS", "TEXT", "THAE", "THAN", "THAT", "THAW", "THEE", "THEM", "THEN", "THEW", "THEY", "THIN", "THIS", "THON", "THOU", "THRO", "THRU", "THUD", "THUG", "THUS", "TICS", "TIDE", "TIDS", "TIDY", "TIED", "TIER", "TIES", "TIFF", "TIKE", "TIKI", "TILE", "TILL", "TILS", "TILT", "TIME", "TINE", "TING", "TINS", "TINT", "TINY", "TIPS", "TIRE", "TIRL", "TIRO", "TITS", "TIVY", "TOAD", "TOBY", "TOCK", "TOCO", "TODS", "TODY", "TOED", "TOES", "TOFF", "TOFT", "TOFU", "TOGA", "TOGS", "TOIL", "TOIT", "TOKE", "TOLA", "TOLD", "TOLE", "TOLL", "TOLU", "TOMB", "TOME", "TOMS", "TONE", "TONG", "TONS", "TONY", "TOOK", "TOOL", "TOOM", "TOON", "TOOT", "TOPE", "TOPH", "TOPI", "TOPO", "TOPS", "TORA", "TORC", "TORE", "TORI", "TORN", "TORO", "TORR", "TORS", "TORT", "TORY", "TOSH", "TOSS", "TOST", "TOTE", "TOTS", "TOUR", "TOUT", "TOWN", "TOWS", "TOWY", "TOYS", "TRAD", "TRAM", "TRAP", "TRAY", "TREE", "TREF", "TREK", "TRES", "TRET", "TREY", "TRIG", "TRIM", "TRIO", "TRIP", "TROD", "TROG", "TROP", "TROT", "TROW", "TROY", "TRUE", "TRUG", "TSAR", "TSKS", "TUBA", "TUBE", "TUBS", "TUCK", "TUFA", "TUFF", "TUFT", "TUGS", "TULE", "TUMP", "TUNA", "TUNE", "TUNG", "TUNS", "TUPS", "TURD", "TURF", "TURK", "TURN", "TUSH", "TUSK", "TUTS", "TUTU", "TWAE", "TWAS", "TWEE", "TWIG", "TWIN", "TWIT", "TWOS", "TYEE", "TYER", "TYES", "TYIN", "TYKE", "TYNE", "TYPE", "TYPO", "TYPP", "TYPY", "TYRE", "TYRO", "TZAR",
    "UDON", "UDOS", "UGHS", "UGLY", "UKES", "ULAN", "ULNA", "ULUS", "ULVA", "UMBO", "UMPS", "UNAI", "UNAU", "UNBE", "UNCI", "UNCO", "UNDE", "UNDO", "UNDY", "UNIT", "UNTO", "UPAS", "UPBY", "UPDO", "UPON", "URBS", "URDS", "UREA", "URGE", "URIC", "URNS", "URPS", "URSA", "URUS", "USED", "USER", "USES", "UTAS", "UTES", "UVEA",
    "VACS", "VAGI", "VAIL", "VAIN", "VAIR", "VALE", "VAMP", "VANE", "VANG", "VANS", "VARA", "VARS", "VARY", "VASA", "VASE", "VAST", "VATS", "VATU", "VAUS", "VAVS", "VAWS", "VEAL", "VEEP", "VEER", "VEES", "VEIL", "VEIN", "VELA", "VELD", "VENA", "VEND", "VENT", "VERB", "VERT", "VERY", "VEST", "VETO", "VETS", "VEXT", "VIAL", "VIBE", "VICE", "VIDE", "VIDS", "VIED", "VIER", "VIES", "VIEW", "VIGA", "VIGS", "VILE", "VILL", "VIMS", "VINA", "VINE", "VINO", "VINS", "VINT", "VINY", "VIOL", "VIRL", "VISA", "VISE", "VITA", "VITE", "VIVA", "VIVE", "VLOG", "VOID", "VOLE", "VOLT", "VOTE", "VOWS", "VROW", "VUGG", "VUGH", "VUGS",
    "WABS", "WACK", "WADE", "WADS", "WADY", "WAES", "WAFF", "WAFT", "WAGE", "WAGS", "WAIF", "WAIL", "WAIN", "WAIR", "WAIT", "WAKA", "WAKE", "WALK", "WALL", "WALY", "WAME", "WAND", "WANE", "WANG", "WANS", "WANT", "WANY", "WAPS", "WARD", "WARE", "WARK", "WARM", "WARN", "WARP", "WARS", "WART", "WARY", "WASH", "WASP", "WAST", "WATS", "WATT", "WAUK", "WAUL", "WAVE", "WAVY", "WAWL", "WAWS", "WAXY", "WAYS", "WEAK", "WEAL", "WEAN", "WEAR", "WEBS", "WEDS", "WEED", "WEEK", "WEEL", "WEEN", "WEEP", "WEER", "WEES", "WEET", "WEFT", "WEIR", "WELD", "WELL", "WELT", "WEND", "WENS", "WENT", "WEPT", "WERE", "WERT", "WEST", "WETS", "WHAM", "WHAP", "WHAT", "WHEN", "WHET", "WHEW", "WHEY", "WHID", "WHIG", "WHIM", "WHIN", "WHIP", "WHIR", "WHIT", "WHIZ", "WHOA", "WHOM", "WHOP", "WHUP", "WHYS", "WICH", "WICK", "WIDE", "WIFE", "WIGS", "WILD", "WILE", "WILL", "WILT", "WILY", "WIMP", "WIND", "WINE", "WING", "WINK", "WINO", "WINS", "WINY", "WIPE", "WIRE", "WIRY", "WISE", "WISH", "WISP", "WISS", "WIST", "WITE", "WITH", "WITS", "WIVE", "WOAD", "WOES", "WOKE", "WOKS", "WOLD", "WOLF", "WOMB", "WONK", "WONS", "WONT", "WOOD", "WOOF", "WOOL", "WOOS", "WORD", "WORE", "WORK", "WORM", "WORN", "WORT", "WOVE", "WOWS", "WRAP", "WREN", "WRIT", "WUSS", "WYCH", "WYES", "WYLE", "WYND", "WYNN", "WYNS", "WYTE", "WELP",
    "XRAY", "XYST",
    "YACK", "YAFF", "YAGI", "YAKS", "YALD", "YAMS", "YANG", "YANK", "YAPS", "YARD", "YARE", "YARN", "YAUD", "YAUP", "YAWL", "YAWN", "YAWP", "YAWS", "YAYS", "YEAH", "YEAN", "YEAR", "YEAS", "YECH", "YEGG", "YELD", "YELK", "YELL", "YELP", "YENS", "YEPS", "YETI", "YETT", "YEUK", "YEWS", "YILL", "YINS", "YIPE", "YIPS", "YIRD", "YIRR", "YLEM", "YOBS", "YOCK", "YODS", "YOGA", "YOGI", "YOKE", "YOKS", "YOLK", "YOND", "YONI", "YORE", "YOUR", "YOWS", "YUAN", "YUCA", "YUCH", "YUCK", "YUGA", "YUKS", "YULE", "YUPS", "YURT", "YUTZ", "YWIS",
    "ZAGS", "ZANY", "ZAPS", "ZARF", "ZEAL", "ZEBU", "ZEDS", "ZEES", "ZEIN", "ZEKS", "ZEPS", "ZERK", "ZERO", "ZEST", "ZETA", "ZIGS", "ZILL", "ZINC", "ZINE", "ZING", "ZINS", "ZIPS", "ZITI", "ZITS", "ZOEA", "ZOIC", "ZONA", "ZONE", "ZONK", "ZOOM", "ZOON", "ZOOS", "ZORI", "ZOUK", "ZYME"

].map(word => word.toUpperCase());

// --- 4. Basic Word Validation Functions ---
/**
 * Checks if a word exists in our predefined dictionary.
 * @param {string} word The word to check.
 * @returns {boolean} True if the word is valid, false otherwise.
 */
function isValidWord(word) {
    return dictionary.includes(word.toUpperCase());
}

/**
 * Checks if a 'nextWord' is a valid Word Morph step from 'currentWord'.
 * - Must be the same length.
 * - Must differ by exactly one letter.
 * - The changed letter must be in the same position.
 * @param {string} currentWord The word currently at the end of the chain.
 * @param {string} nextWord The word the player is trying to add.
 * @returns {boolean} True if it's a valid morph step, false otherwise.
 */
function isValidMorphStep(currentWord, nextWord) {
    if (currentWord.length !== nextWord.length) {
        return false; // Words must be the same length
    }

    let diffCount = 0;
    for (let i = 0; i < currentWord.length; i++) {
        if (currentWord[i] !== nextWord[i]) {
            diffCount++;
        }
    }
    // Must differ by exactly one letter
    return diffCount === 1;
}

// --- 5. Game Initialization & Start ---
/**
 * Initializes or resets the game state and UI for a new puzzle.
 * This is the main function that sets up a new game round.
 */
/**
 * Initializes or resets the game state and UI for a new puzzle.
 * This is the main function that sets up a new game round.
 * @param {object|null} puzzleOverride An optional puzzle object to use instead of fetching from Firebase.
 */
async function initializeGame(puzzleOverride = null) {
    console.log("initializeGame() function started!");
    // Hide Share Result button at the start of any new game
    shareResultBtn.classList.add('hidden');
    shareResultBtn.classList.remove('block');
    // Hide Optimal Path Display Section at the start of a new game
    optimalPathDisplaySection.classList.add('hidden');
    optimalPathDisplaySection.classList.remove('block');
    // Hide end-game buttons at the start of any new game
    newGameBtn.classList.add('hidden');
    newGameBtn.classList.remove('block');
    randomPuzzleBtn.classList.add('hidden');
    randomPuzzleBtn.classList.remove('block');
    // Hide replay button at the start of any new game
    replayPuzzleBtn.classList.add('hidden');
    replayPuzzleBtn.classList.remove('block');
    // Show Give Up button
    giveUpBtn.classList.remove('hidden');
    // Hide View Solution button at the start of any new game
    viewSolutionBtn.classList.add('hidden');
    viewSolutionBtn.classList.remove('block');

    // --- Determine Puzzle Source: Override or Firebase Daily Puzzle ---
    let selectedPuzzleData;

    if (puzzleOverride) { // If a puzzle object was passed directly (e.g., from "Play Random Puzzle" button)
        selectedPuzzleData = puzzleOverride;
        console.log(`Using override puzzle: ${selectedPuzzleData.start_word} to ${selectedPuzzleData.target_word}`);
    } else { // Otherwise, try to load today's puzzle from Firebase
        const today = new Date();
        const todayString = today.getFullYear() + '-' +
            String(today.getMonth() + 1).padStart(2, '0') + '-' +
            String(today.getDate()).padStart(2, '0');

        try {
            const dailyPuzzlesRef = collection(window.firestoreDb, `dailyPuzzles`);
            const q = query(dailyPuzzlesRef, where("__name__", "==", todayString));
            const querySnapshot = await getDocs(q);

            if (!querySnapshot.empty) {
                selectedPuzzleData = querySnapshot.docs[0].data();
                console.log(`Successfully loaded puzzle for ${todayString}: ${selectedPuzzleData.start_word} to ${selectedPuzzleData.target_word}`);
            } else {
                console.warn(`No puzzle found for ${todayString}. Using default puzzle.`);
                selectedPuzzleData = { // Default fallback puzzle
                    start_word: "READ",
                    target_word: "ROSE",
                    optimal_path_length: 6,
                    optimal_path: ['READ', 'HEAD', 'HELD', 'HOLD', 'HOLE', 'ROLE', 'ROSE'],
                    difficulty: "Medium"
                };
                window.showMessage(`No puzzle for ${todayString}. Using default READ to ROSE.`, 5000);
            }
        } catch (e) {
            console.error("Error loading daily puzzle from Firebase: ", e);
            window.showMessage("Error loading daily puzzle. Using default.", 5000);
            selectedPuzzleData = { // Default fallback puzzle on error
                start_word: "READ",
                target_word: "ROSE",
                optimal_path_length: 6,
                optimal_path: ['READ', 'HEAD', 'HELD', 'HOLD', 'HOLE', 'ROLE', 'ROSE'],
                difficulty: "Medium"
            };
        }
    }
    // --- End Determine Puzzle Source ---

    // --- Apply Selected Puzzle Data to Game State Variables ---
    currentSeedWord = selectedPuzzleData.start_word;
    currentTargetWord = selectedPuzzleData.target_word;
    currentDifficulty = selectedPuzzleData.difficulty;
    optimalPathLength = selectedPuzzleData.optimal_path_length;
    window.currentOptimalPath = selectedPuzzleData.optimal_path; // Store the full optimal path

    // --- Reset Game State for a New Round ---
    currentChain = [currentSeedWord]; // Start chain with the seed word
    currentScore = 0; // Reset score
    gameTimer = 0; // Reset timer
    clearInterval(timerInterval); // Clear any old timer
    gameInProgress = true; // Set game active

    // Reset power-up counts and track used ones for a new game
    powerUpCounts = { // Reset AVAILABLE power-ups
        hint: 0,
        swap: 0,
        skip: 0
    };
    powerUpsUsedThisGame = { // Reset *USED* power-ups
        hint: 0,
        swap: 0,
        skip: 0
    };

    // Give player initial hint for the day (or based on daily allowance)
    powerUpCounts.hint = 2; // Give 2 hint to start

    // --- Update UI Elements ---
    seedWordDisplay.textContent = currentSeedWord;
    targetWordDisplay.textContent = currentTargetWord;
    difficultyDisplay.textContent = currentDifficulty;
    userGuessInput.value = ''; // Clear input field
    userGuessInput.disabled = false; // Enable input
    submitGuessBtn.disabled = false; // Enable submit button

    renderWordChain(); // Display the seed word
    updateScoreDisplay();
    updatePowerUpDisplays(); // Update power-up button states

    // Start the game timer
    startTimer();

    // Show initial puzzle message (will use loaded words)
    window.showMessage(`Today's puzzle: ${currentSeedWord} to ${currentTargetWord}!`, 5000);
    // loadLeaderboard is called by the main DOMContentLoaded trigger after full Firebase init
}

// --- 6. Core Game Loop Functions ---

/**
 * Handles a player's guess submitted via input or button click.
 */
function processGuess() {
    if (!gameInProgress) { // Prevent input if game is not active
        window.showMessage("Game not in progress. Refresh for a new puzzle.", 5000);
        return; // Stop function execution here
    }

    const guess = userGuessInput.value.trim().toUpperCase(); // Get and clean player's input
    userGuessInput.value = ''; // Clear input field immediately

    // --- Visual Feedback Logic ---
    // Reset to default border style directly
    userGuessInput.style.border = '2px solid #D1D5DB'; // Tailwind's border-2 border-gray-300 equivalent

    // 1. Check if input is empty
    if (guess.length === 0) {
        window.showMessage("Please enter a word.", 5000);
        // No flash for empty input, just message
        // Restore default border immediately for empty input
        userGuessInput.classList.add('border-2', 'border-gray-300');
        return; // Stop function execution here
    }

    const lastWordInChain = currentChain[currentChain.length - 1]; // Get the last word player entered

    // 2. Check if word is in dictionary
    if (!isValidWord(guess)) {
        // Apply strong red border flash directly
        userGuessInput.style.border = '8px solid #EF4444'; // Tailwind's border-8 border-red-500 equivalent
        setTimeout(() => {
            userGuessInput.style.border = '2px solid #D1D5DB'; // Restore default border
        }, 1000); // Flash for 1 second
        // Add a time penalty for invalid words
        gameTimer += 4; // Add 5 seconds penalty
        window.showMessage(`'${guess}' is not a valid word.`, 5000);
        return; // Stop function execution here
    }

    // 3. Check if word follows morph rule (one letter different)
    if (!isValidMorphStep(lastWordInChain, guess)) {
        // Apply strong red border flash directly
        userGuessInput.style.border = '8px solid #EF4444'; // Tailwind's border-8 border-red-500 equivalent
        setTimeout(() => {
            userGuessInput.style.border = '2px solid #D1D5DB'; // Restore default border
        }, 1000); // Flash for 1 second
        // Add a time penalty for invalid morph steps
        gameTimer += 4; // Add 5 seconds penalty
        window.showMessage(`'${guess}' is not a valid morph from '${lastWordInChain}'. One letter, same position!`, 5000);
        return; // Stop function execution here
    }

    // If all checks pass, the guess is valid!
    // Apply strong green border flash directly
    userGuessInput.style.border = '8px solid #22C55E'; // Tailwind's border-8 border-green-500 equivalent
    setTimeout(() => {
        userGuessInput.style.border = '2px solid #D1D5DB'; // Restore default border
    }, 1000); // Flash for 1 second

    currentChain.push(guess); // Add the valid word to the chain
    renderWordChain(); // Update the visual display of the chain

    // Check for win condition
    if (guess === currentTargetWord) {
        endGame(true); // Player won!
    }
}

/**
 * Renders the current word chain to the HTML list.
 */
function renderWordChain() {
    wordChainList.innerHTML = ''; // Clear existing list
    currentChain.forEach(word => {
        const listItem = document.createElement('li');
        listItem.textContent = word;
        listItem.className = 'py-1 text-gray-800 text-2xl md:text-3xl font-bold word-chain-item-enter'; // Add animation class
        wordChainList.appendChild(listItem);
    });
    // Scroll to the bottom of the list for long chains
    wordChainList.scrollTop = wordChainList.scrollHeight;
}

/**
 * Updates the score display in the UI.
 */
function updateScoreDisplay() {
    currentScoreDisplay.textContent = currentScore;
}

/**
 * Updates the power-up count displays and button enabled states.
 */
function updatePowerUpDisplays() {
    hintCountDisplay.textContent = powerUpCounts.hint;
    swapCountDisplay.textContent = powerUpCounts.swap;
    skipCountDisplay.textContent = powerUpCounts.skip;

    hintBtn.disabled = powerUpCounts.hint <= 0;
    swapBtn.disabled = powerUpCounts.swap <= 0;
    skipBtn.disabled = powerUpCounts.skip <= 0;

    hintBtn.classList.toggle('opacity-50', powerUpCounts.hint <= 0);
    hintBtn.classList.toggle('cursor-not-allowed', powerUpCounts.hint <= 0);
    swapBtn.classList.toggle('opacity-50', powerUpCounts.swap <= 0);
    swapBtn.classList.toggle('cursor-not-allowed', powerUpCounts.swap <= 0);
    skipBtn.classList.toggle('opacity-50', powerUpCounts.skip <= 0);
    skipBtn.classList.toggle('cursor-not-allowed', powerUpCounts.skip <= 0);
}

/**
 * Starts the game timer.
 */
/**
/**
 * Starts or resumes the game timer.
 * This function is called by initializeGame() and showTutorialStep().
 */
function startTimer() {
    if (timerInterval) { // Clear any existing interval to prevent multiple timers
        clearInterval(timerInterval);
    }

    // CRITICAL CHANGE: Only reset gameTimer to 0 if it's a new game initialization
    // (i.e., initializeGame() just set gameInProgress to true and chain is only seed word)
    // This prevents resetting when resuming from a mid-game tutorial.
    if (gameInProgress && currentChain.length === 1 && gameTimer === 0) {
        gameTimer = 0;
    }

    // Ensure display is updated correctly on start/resume
    const minutes = Math.floor(gameTimer / 60);
    const seconds = gameTimer % 60;
    timerDisplay.textContent = `${minutes}:${String(seconds).padStart(2, '0')}`;

    timerInterval = setInterval(() => {
        gameTimer++;
        const currentMinutes = Math.floor(gameTimer / 60);
        const currentSeconds = gameTimer % 60;
        timerDisplay.textContent = `${currentMinutes}:${String(currentSeconds).padStart(2, '0')}`;

    }, 1000); // Update every second
}

/**
 * Ends the game and calculates the final score.
 * @param {boolean} won True if the player reached the target word.
 */
function endGame(won) {
    if (!gameInProgress) return; // Prevent multiple calls
    gameInProgress = false; // Set game inactive

    clearInterval(timerInterval); // Stop the timer
    userGuessInput.disabled = true; // Disable input
    submitGuessBtn.disabled = true; // Disable submit button
    hintBtn.disabled = true; // Disable power-up buttons
    swapBtn.disabled = true;
    skipBtn.disabled = true;

    // Calculate final score using the dedicated function
    currentScore = calculateFinalScore(won, currentChain.length, gameTimer, powerUpsUsedThisGame, optimalPathLength);
    updateScoreDisplay(); // Update UI with final score

    window.showMessage(won ? `Congratulations! You morphed '${currentSeedWord}' to '${currentTargetWord}'! Final Score: ${currentScore}` : `Time's up! Game over. Final Score: ${currentScore}`, 5000);
    console.log("Game ended. Player chain:", currentChain);
    console.log("Time taken:", gameTimer, "seconds.");
    console.log("Final Calculated Score (after endGame):", currentScore);

    // Call saveScore function if the player won
    // Call saveScore function if the game ended (win or lose)
    if (window.firestoreDb && window.currentUserId) { // CRITICAL CHANGE: Removed '&& won'
        saveScore(window.currentUserId, {
            score: currentScore,
            chain: currentChain,
            time: gameTimer,
            puzzleId: `${currentSeedWord}-${currentTargetWord}-${optimalPathLength}`,
            date: new Date().toISOString(),
            difficulty: currentDifficulty
        });
        // Determine the encouraging feedback message based on score (NEW LOGIC STARTS HERE)
        let feedbackMessage = "";
        if (currentScore >= 9) { // High score, likely perfect or near-perfect
            feedbackMessage = "Amazing job!";
        } else if (currentScore >= 6) { // Good score
            feedbackMessage = "Great work!";
        } else if (currentScore > 0) { // Some score, but not high
            feedbackMessage = "Keep practicing!";
        } else { // Score of 0 (timed out or gave up)
            feedbackMessage = "Don't give up! You'll get it next time!";
        }

        const minutes = Math.floor(gameTimer / 60);
        const seconds = gameTimer % 60;
        const formattedTime = `${minutes}:${String(seconds).padStart(2, '0')}`;

        // First message: Encouraging note (appears first for 2 seconds)
        window.showMessage(feedbackMessage, 2000);

        // Second message: Score/Time/Save confirmation (appears after first message fades, for 5 seconds)
        setTimeout(() => {
            window.showMessage(`Score ${currentScore} (Time: ${formattedTime}) saved and leaderboard updated!`, 5000);
            loadLeaderboard(newSubmissionId); // Load leaderboard after the message is displayed
        }, 2500); // Start showing this message 0.5 seconds after the first one fades

    } else { // If Firebase/User not ready, just show basic message (no save)
        const minutes = Math.floor(gameTimer / 60);
        const seconds = gameTimer % 60;
        const formattedTime = `${minutes}:${String(seconds).padStart(2, '0')}`;
        window.showMessage(`Game ended. Final Score: ${currentScore} (Time: ${formattedTime}). Not saved (Firebase not ready).`, 5000);
    }
    // Show New Game button
    newGameBtn.classList.remove('hidden');
    newGameBtn.classList.add('block'); // Make it visible
    // Also show the Random Puzzle button
    randomPuzzleBtn.classList.remove('hidden');
    randomPuzzleBtn.classList.add('block');
    // Hide Optimal Path Display Section by default at game end, show button instead
    optimalPathDisplaySection.classList.add('hidden');
    optimalPathDisplaySection.classList.remove('block'); // Ensure it's hidden

    // Show the View Solution button
    viewSolutionBtn.classList.remove('hidden');
    viewSolutionBtn.classList.add('block');
    // Also show the Replay Puzzle button
    replayPuzzleBtn.classList.remove('hidden');
    replayPuzzleBtn.classList.add('block');
    // Show Share Result button
    shareResultBtn.classList.remove('hidden');
    shareResultBtn.classList.add('block');
    // Hide Give Up button
    giveUpBtn.classList.add('hidden');
}

/**
 * Saves a player's score to Firestore.
 * @param {string} userId The current authenticated user's ID.
 * @param {object} scoreData The data object containing the score, chain, time, etc.
 */
async function saveScore(userId, scoreData) {
    try {
        const scoresCollection = collection(window.firestoreDb, `artifacts/${window.appId}/public/data/wordMorphScores`);

        // Generate the submissionId ONCE and use it consistently (CRITICAL CHANGE HERE)
        const newSubmissionId = crypto.randomUUID();

        await addDoc(scoresCollection, {
            userId: userId,
            score: scoreData.score,
            chain: scoreData.chain,
            time: gameTimer, // Use gameTimer directly as it's the final time
            puzzleId: `${currentSeedWord}-${currentTargetWord}-${optimalPathLength}`, // Use current puzzle data
            date: new Date().toISOString(),
            difficulty: currentDifficulty,
            submissionId: newSubmissionId, // Use the generated ID here
            timestamp: new Date()
        });

        console.log("Score successfully written to Firestore!");
        const minutes = Math.floor(gameTimer / 60);
        const seconds = gameTimer % 60;

        // Pass the SAME generated ID to loadLeaderboard (CRITICAL CHANGE HERE)
        loadLeaderboard(newSubmissionId);

    } catch (e) {
        console.error("Error adding document to Firestore: ", e);
        window.showMessage("Error saving score.", 3000);
    }
}

/**
 * Loads and displays the top scores for the current puzzle from Firestore.
 */
/**
 * Loads and displays the top scores for the current puzzle from Firestore.
 * This function uses the global `window.firestoreDb` and `window.appId`
 * which are set by the Firebase script in `index.html`.
 */
async function loadLeaderboard(highlightSubmissionId = null) { // Added highlightSubmissionId parameter
    if (!leaderboardList) { // Defensive check: ensure HTML element exists
        console.error("Leaderboard HTML element not found.");
        return;
    }
    leaderboardList.innerHTML = '<li class="text-gray-600 italic text-center py-2">Loading scores...</li>'; // Show loading message

    try {
        // We trust the main DOMContentLoaded interval to ensure window.firestoreDb and window.appId are set.
        // No need for a redundant internal check here, as it was causing timing issues.
        const scoresCollectionRef = collection(window.firestoreDb, `artifacts/${window.appId}/public/data/wordMorphScores`);

        // Filter by current puzzleId
        const q = query(
            scoresCollectionRef,
            where("puzzleId", "==", `${currentSeedWord}-${currentTargetWord}-${optimalPathLength}`)
        );

        const querySnapshot = await getDocs(q);
        let scores = [];
        querySnapshot.forEach((doc) => {
            scores.push(doc.data());
        });

        // Sort scores in JavaScript (Score: descending, then Time: ascending)
        scores.sort((a, b) => {
            if (a.score === b.score) {
                return a.time - b.time; // Shorter time is better for same score
            }
            return b.score - a.score; // Higher score is better
        });

        leaderboardList.innerHTML = ''; // Clear previous leaderboard content
        if (scores.length === 0) {
            const listItem = document.createElement('li');
            listItem.className = 'text-gray-600 italic text-center py-2';
            listItem.textContent = 'Play to see how you stack up on the Leaderboard!';
            leaderboardList.appendChild(listItem);
        } else {
            scores.slice(0, 10).forEach((scoreData, index) => { // Display top 10 scores
                const listItem = document.createElement('li');
                listItem.className = 'flex justify-between items-center py-1 border-b border-gray-200 last:border-b-0 px-2';

                // Shorten userId for display
                let displayUserId = scoreData.userId;
                if (scoreData.userId && scoreData.userId.length > 8) {
                    displayUserId = scoreData.userId.substring(0, 8) + '...';
                } else if (!scoreData.userId) { // Fallback for undefined userId
                    displayUserId = 'Anonymous';
                }

                // Highlight current user's score
                let displayName = displayUserId;
                if (window.currentUserId && scoreData.userId === window.currentUserId) {
                    displayName = "You (" + displayUserId + ")";
                    listItem.className += ' font-bold text-blue-700'; // Make current user's score bold/blue
                }

                const minutes = Math.floor(scoreData.time / 60);
                const seconds = scoreData.time % 60;
                const timeFormatted = `${minutes}:${seconds < 10 ? '0' : ''}${seconds}`;

                // Apply a special highlight if this is the score just submitted
                if (highlightSubmissionId && scoreData.submissionId === highlightSubmissionId) {
                    listItem.className += ' bg-blue-100 border-blue-500 border-l-4'; // Add distinct highlight classes
                }
                listItem.innerHTML = `
                    <span class="w-1/4">${index + 1}.</span>
                    <span class="w-1/2">${displayName}</span>
                    <span class="w-1/4 text-right">${scoreData.score}</span>
                    <span class="w-1/4 text-right">${timeFormatted}</span>
                `;
                leaderboardList.appendChild(listItem);
            });
        }

    } catch (e) {
        console.error("Error loading leaderboard: ", e);
        leaderboardList.innerHTML = '<li class="text-red-500 text-center py-2">Error loading scores. Please check console for Firebase security rules or connection issues.</li>';
    }
}

// --- 5.5. Score Calculation Function ---
/**
 * Calculates the player's final score based on game rules.
 * @param {boolean} won True if the player reached the target word.
 * @param {number} chainLength The number of words in the player's chain (including seed).
 * @param {number} timeTaken The time taken in seconds.
 * @param {object} powerUpsUsed Counts of each power-up type used.
 * @param {number} optimalLength The pre-determined optimal path length for the puzzle (transitions).
 * @returns {number} The calculated final score.
 */
function calculateFinalScore(won, chainLength, timeTaken, powerUpsUsed, optimalLength) {
    console.log("--- Calculating Final Score ---");
    console.log("Input: won =", won, ", chainLength =", chainLength, ", timeTaken =", timeTaken, ", powerUpsUsed =", powerUpsUsed, ", optimalLength =", optimalLength);

    // CRITICAL CHANGE: If game not won, return 0 immediately for final score
    if (!won) {
        console.log("Score Component: Final Score is 0 (Did not win).");
        return 0;
    }

    let score = 0;
    const playerTransitions = chainLength - 1; // Number of steps player took

    // ... rest of the scoring logic (Completion Bonus, Efficiency, Power-Up, Time)
    // These will now only run if 'won' is true.

    // 1. Completion Bonus (2 points) - Adjusted
    if (won) {
        score += 2; // Changed from 3 to 2 points
        console.log("Score Component: Completion Bonus (+2)");
    } else {
        score += 0;
        console.log("Score Component: Completion Bonus (+0) - Did not win.");
    }

    // 2. Efficiency Bonus (4 points)
    // Target Number of transitions = Optimal Path Length + 1
    const targetForEfficiency = optimalLength + 1;

    if (won) { // Only award efficiency if game was won
        console.log("Efficiency Check: Player transitions =", playerTransitions, ", Optimal Length =", optimalLength, ", Target for Efficiency =", targetForEfficiency);
        if (playerTransitions <= optimalLength) { // Beats the Target Number (found Optimal Path)
            score += 4;
            console.log("Score Component: Efficiency Bonus (+4) - Beat Target");
        } else if (playerTransitions === targetForEfficiency) { // Meets the Target Number
            score += 3;
            console.log("Score Component: Efficiency Bonus (+3) - Met Target");
        } else if (playerTransitions === targetForEfficiency + 1) { // One step longer
            score += 2;
            console.log("Score Component: Efficiency Bonus (+2) - One step longer");
        } else if (playerTransitions === targetForEfficiency + 2) { // Two steps longer
            score += 1;
            console.log("Score Component: Efficiency Bonus (+1) - Two steps longer");
        } else { // Three or more steps longer
            score += 0;
            console.log("Score Component: Efficiency Bonus (+0) - Three or more steps longer");
        }
    } else {
        console.log("Score Component: Efficiency Bonus (+0) - Game not won.");
    }

    // 3. Power-Up Usage (2 points) - More granular
    const totalPowerUpsUsed = powerUpsUsed.hint + powerUpsUsed.swap + powerUpsUsed.skip;
    console.log("Power-Up Check: Hint Used =", powerUpsUsed.hint, ", Swap Used =", powerUpsUsed.swap, ", Skip Used =", powerUpsUsed.skip, ", Total Used =", totalPowerUpsUsed);
    if (powerUpsUsed.hint === 0) { // 0 hints used
        score += 2;
        console.log("Score Component: Power-Up Usage (+2) - No hints used.");
    } else if (powerUpsUsed.hint === 1) { // 1 hint used
        score += 1;
        console.log("Score Component: Power-Up Usage (+1) - One hint used.");
    } else { // 2 or more hints used
        score += 0;
        console.log("Score Component: Power-Up Usage (+0) - Two or more hints used.");
    }

    // 4. Time Bonus (2 points) - More granular
    console.log("Time Check: Time Taken =", timeTaken, "seconds.");
    if (timeTaken < 60) { // Under 1 minute
        score += 2;
        console.log("Score Component: Time Bonus (+2) - Under 60 seconds.");
    } else if (timeTaken < 90) { // Under 1 minute 30 seconds
        score += 1.5;
        console.log("Score Component: Time Bonus (+1.5) - Under 90 seconds.");
    } else if (timeTaken < 120) { // Under 2 minutes
        score += 1;
        console.log("Score Component: Time Bonus (+1) - Under 120 seconds.");
    } else if (timeTaken < 150) { // Under 2 minutes 30 seconds
        score += 0.5;
        console.log("Score Component: Time Bonus (+0.5) - Under 150 seconds.");
    } else { // Over 2 minutes 30 seconds
        score += 0;
        console.log("Score Component: Time Bonus (+0) - Over 150 seconds.");
    }

    console.log("--- End Score Calculation ---");
    return score;
}

// --- 7. Event Listeners ---
submitGuessBtn.addEventListener('click', processGuess);
userGuessInput.addEventListener('keypress', function (event) {
    if (event.key === 'Enter') {
        processGuess();
    }
});
// Event listener for Give Up button
giveUpBtn.addEventListener('click', () => {
    if (!gameInProgress) { // Prevent action if no game is active
        window.showMessage("No game in progress to give up.", 3000);
        return;
    }
    window.showMessage("You gave up! Displaying solution and offering new puzzles.", 5000);
    endGame(false); // End the game as a loss (not won)
});
// Power-up button placeholders (will add specific logic later)
hintBtn.addEventListener('click', () => {
    if (powerUpCounts.hint > 0) { // Check if hints are available
        powerUpCounts.hint--; // Decrement available hints
        powerUpsUsedThisGame.hint++; // Increment count of hints *used this game*
        updatePowerUpDisplays(); // Update UI for hint count
        // PASTE THIS CODE BLOCK HERE, after updatePowerUpDisplays();
        // REPLACE the existing hint logic block with this:
        const lastWord = currentChain[currentChain.length - 1];
        let hintWord = null;

        // Find the index of the last word in the current chain within the optimal path
        const lastWordIndexInOptimalPath = window.currentOptimalPath.indexOf(lastWord);

        if (lastWordIndexInOptimalPath !== -1 && lastWordIndexInOptimalPath < window.currentOptimalPath.length - 1) {
            // If the current word is on the optimal path and not the target word,
            // the hint is the *next* word on the optimal path.
            hintWord = window.currentOptimalPath[lastWordIndexInOptimalPath + 1];
            window.showMessage(`Hint: The next optimal step is '${hintWord}'!`, 5000);
        } else {
            // Fallback: If current word is not on optimal path, or is the target,
            // provide a random valid morph from the dictionary (current behavior).
            let possibleNextWords = [];
            for (let i = 0; i < dictionary.length; i++) {
                const dictWord = dictionary[i];
                if (isValidMorphStep(lastWord, dictWord) && dictWord !== lastWord) {
                    possibleNextWords.push(dictWord);
                }
            }
            if (possibleNextWords.length > 0) {
                hintWord = possibleNextWords[Math.floor(Math.random() * possibleNextWords.length)];
                window.showMessage(`Hint: Try '${hintWord}' next! (Not on optimal path)`, 5000);
            } else {
                window.showMessage("No direct hint available from the dictionary for this word.", 5000);
            }
        }
    } else {
        window.showMessage("No hints available!", 5000);
    }
});
swapBtn.addEventListener('click', () => { window.showMessage("Swap power-up clicked (logic coming soon!)", 5000); });
skipBtn.addEventListener('click', () => { window.showMessage("Skip power-up clicked (logic coming soon!)", 5000); });
// Event listener for How to Play button (NEW CODE STARTS HERE)
// Event listener for How to Play button
// Event listener for How to Play button (NEW CORRECTED CODE STARTS HERE)
howToPlayBtn.addEventListener('click', () => {
    // Pause the game state before showing tutorial
    clearInterval(timerInterval);
    gameInProgress = false;
    userGuessInput.disabled = true;
    submitGuessBtn.disabled = true;
    hintBtn.disabled = true; // Disable power-up buttons during tutorial
    swapBtn.disabled = true;
    skipBtn.disabled = true;

    inTutorialMode = true; // Set flag: we are entering tutorial from mid-game
    currentTutorialStep = 0; // Always start tutorial from step 0 when clicked manually
    showTutorialStep();      // Show the tutorial modal
});
// NEW CORRECTED CODE ENDS HERE
// NEW CODE ENDS HERE
// Event listener for New Game button
newGameBtn.addEventListener('click', () => {
    // Hide New Game button
    newGameBtn.classList.add('hidden');
    newGameBtn.classList.remove('block');

    // Re-initialize the game (this will load today's puzzle again)
    window.initializeGameApp();
});
// Event listener for Play Random Puzzle button (NEW CODE STARTS HERE)
randomPuzzleBtn.addEventListener('click', () => {
    // Hide both end-game buttons
    newGameBtn.classList.add('hidden');
    newGameBtn.classList.remove('block');
    randomPuzzleBtn.classList.add('hidden');
    randomPuzzleBtn.classList.remove('block');

    // Select a random puzzle from the hardcoded list
    const randomIndex = Math.floor(Math.random() * RANDOM_PUZZLES.length);
    const selectedPuzzle = RANDOM_PUZZLES[randomIndex];

    // Override current puzzle variables with the random puzzle
    currentSeedWord = selectedPuzzle.start_word;
    currentTargetWord = selectedPuzzle.target_word;
    currentDifficulty = selectedPuzzle.difficulty;
    optimalPathLength = selectedPuzzle.optimal_path_length;
    window.currentOptimalPath = selectedPuzzle.optimal_path; // Important for smart hint

    console.log(`Loading random puzzle: ${currentSeedWord} to ${currentTargetWord}`);
    window.showMessage(`Playing a random puzzle: ${currentSeedWord} to ${currentTargetWord}!`, 5000);

    // Re-initialize the game with the new random puzzle
    window.initializeGameApp(selectedPuzzle);
});

// Event listener for Play Same Puzzle Again button (NEW CODE STARTS HERE)
replayPuzzleBtn.addEventListener('click', () => {
    // Hide all end-game buttons
    newGameBtn.classList.add('hidden');
    newGameBtn.classList.remove('block');
    randomPuzzleBtn.classList.add('hidden');
    randomPuzzleBtn.classList.remove('block');
    replayPuzzleBtn.classList.add('hidden');
    replayPuzzleBtn.classList.remove('block');

    // Re-initialize the game with the *same* puzzle that was just played
    // This puzzle data is already stored in currentSeedWord, currentTargetWord, etc.
    const currentPuzzleData = {
        start_word: currentSeedWord,
        target_word: currentTargetWord,
        optimal_path_length: optimalPathLength,
        optimal_path: window.currentOptimalPath,
        difficulty: currentDifficulty
    };

    console.log(`Replaying puzzle: ${currentSeedWord} to ${currentTargetWord}`);
    window.showMessage(`Replaying: ${currentSeedWord} to ${currentTargetWord}!`, 5000);

    // Re-initialize the game with the current puzzle data
    window.initializeGameApp(currentPuzzleData);
});
// Event listener for View Solution button (NEW CODE STARTS HERE)
viewSolutionBtn.addEventListener('click', () => {
    // Hide the View Solution button itself
    viewSolutionBtn.classList.add('hidden');
    viewSolutionBtn.classList.remove('block');

    // Show the Optimal Path Display Section and render the path
    optimalPathDisplaySection.classList.remove('hidden');
    optimalPathDisplaySection.classList.add('block');

    optimalPathList.innerHTML = ''; // Clear existing list
    if (window.currentOptimalPath && window.currentOptimalPath.length > 0) {
        window.currentOptimalPath.forEach(word => {
            const listItem = document.createElement('li');
            listItem.textContent = word;
            listItem.className = 'py-1 text-gray-800 text-2xl md:text-3xl font-bold';
            optimalPathList.appendChild(listItem);
        });
    } else {
        const listItem = document.createElement('li');
        listItem.textContent = 'Optimal path not available.';
        listItem.className = 'py-1 text-gray-600 italic';
        optimalPathList.appendChild(listItem);
    }
});
// Event listener for Share Result button (NEW CODE STARTS HERE)
shareResultBtn.addEventListener('click', async () => {
    const gameUrl = window.location.href; // Get the current game URL

    // Construct the shareable message (UPDATED LOGIC)
    let shareMessage = `Word Morph Daily Puzzle!\n`;
    shareMessage += `Puzzle: ${currentSeedWord} to ${currentTargetWord}\n`; // Removed Length
    shareMessage += `My Chain Length: ${currentChain.length - 1} Words\n`; // Subtract 1 for transitions
    shareMessage += `My Score: ${currentScore} in ${Math.floor(gameTimer / 60)}:${String(gameTimer % 60).padStart(2, '0')} seconds!\n`;
    shareMessage += `Can you beat it? Play here: ${gameUrl}`; // Removed My Chain

    // Attempt to use the Web Share API (native sharing dialog)
    if (navigator.share) {
        try {
            await navigator.share({
                title: 'Word Morph Daily Puzzle',
                text: shareMessage,

            });
            console.log('Shared successfully!');
            window.showMessage('Shared successfully!', 3000);
        } catch (error) {
            // User cancelled share, or unsupported share target
            if (error.name !== 'AbortError') {
                console.error('Error sharing:', error);
                window.showMessage('Failed to share. Trying to copy to clipboard.', 3000);
                copyToClipboard(shareMessage); // Fallback to clipboard
            } else {
                window.showMessage('Sharing cancelled.', 2000);
            }
        }
    } else {
        // Fallback for browsers that don't support Web Share API (e.g., most desktops)
        console.log('Web Share API not supported. Copying to clipboard.');
        window.showMessage('Web Share API not supported. Copied to clipboard!', 3000);
        copyToClipboard(shareMessage); // Fallback to clipboard
    }
});

// Helper function to copy text to clipboard (reliable fallback)
function copyToClipboard(text) {
    const textarea = document.createElement('textarea');
    textarea.value = text;
    textarea.style.position = 'fixed'; // Avoid scrolling to bottom
    textarea.style.opacity = '0'; // Hide it visually
    document.body.appendChild(textarea);
    textarea.select();
    try {
        document.execCommand('copy');
        window.showMessage('Score details copied to clipboard!', 3000);
    } catch (err) {
        console.error('Failed to copy text: ', err);
        window.showMessage('Failed to copy to clipboard. Please try manually.', 3000);
    }
    document.body.removeChild(textarea);
}
// NEW CODE ENDS HERE
// NEW CODE ENDS HERE
// NEW CODE ENDS HERE
// NEW CODE ENDS HERE


// --- Tutorial Logic ---
const tutorialSteps = [
    { title: "Welcome to Word Morph!", text: "Your goal is to transform the START word into the TARGET word within the shortest MORPH chain possible." }, // Updated text, removed time limit mention as it's gone
    { title: "How to Play (Rule 1)", text: "You can only change ONE letter at a time to create a new word." },
    { title: "How to Play (Rule 2)", text: "Each new word MUST be a real word. Word Morph uses a Scrabble dictionary." }, // Removed dictionary disclaimer
    { title: "How to Play (Rule 3)", text: "Try to find the shortest path to earn more points (Optimal Path Length)." },
    { title: "Sample Morphs", text: "Example 1: CAT → COT → COG → DOG. Example 2: READ → HEAD → HELD → HOLD. (Change one letter at a time!)" }, // New step for sample morphs
    { title: "Penalty!", text: "Submitting an invalid word or an invalid morph will add 5 seconds to your time!" }, // New step for penalty
    { title: "Power-Up!", text: "Use your Hints wisely to help you out! You start with 2 Hints per game." }, // Changed to singular Power-Up, plural Hints, specified count
    { title: "Leaderboard", text: "Your best scores will be saved to the leaderboard. Good luck!" }
];
let currentTutorialStep = 0; // Tracks which step of the tutorial we are on

function showTutorialStep() {
    if (currentTutorialStep < tutorialSteps.length) {
        // Pause the game when tutorial is active
        clearInterval(timerInterval); // Stop the timer
        gameInProgress = false;      // Prevent game actions
        userGuessInput.disabled = true;
        submitGuessBtn.disabled = true;
        hintBtn.disabled = true; // Disable power-up buttons during tutorial
        swapBtn.disabled = true;
        skipBtn.disabled = true;

        tutorialTitle.textContent = tutorialSteps[currentTutorialStep].title;
        tutorialText.textContent = tutorialSteps[currentTutorialStep].text;
        tutorialModal.classList.remove('hidden'); // Show the modal
        // Inside showTutorialStep()'s else block:
    } else { // Tutorial is complete or skipped
        tutorialModal.classList.add('hidden'); // Hide modal
        localStorage.setItem('wordMorphTutorialSeen', 'true'); // Mark tutorial as seen

        if (inTutorialMode) { // If tutorial was opened mid-game (via "How to Play" button)
            inTutorialMode = false; // Reset flag
            // Resume game state (same as previous resume logic)
            gameInProgress = true;
            userGuessInput.disabled = false;
            submitGuessBtn.disabled = false;
            updatePowerUpDisplays();
            startTimer(); // Restart the timer (it will resume from where it left off)
        } else { // This was the first-time tutorial completion
            window.initializeGameApp(null); // Properly initialize a new game
        }
    }
}

// Event listeners for tutorial buttons
tutorialNextBtn.addEventListener('click', () => {
    currentTutorialStep++;
    showTutorialStep();
});

// Inside tutorialSkipBtn.addEventListener:
tutorialSkipBtn.addEventListener('click', () => {
    tutorialModal.classList.add('hidden'); // Hide modal
    localStorage.setItem('wordMorphTutorialSeen', 'true'); // Mark as seen

    if (inTutorialMode) { // If tutorial was opened mid-game
        inTutorialMode = false; // Reset flag
        // Resume game state
        gameInProgress = true;
        userGuessInput.disabled = false;
        submitGuessBtn.disabled = false;
        updatePowerUpDisplays();
        startTimer(); // Restart the timer
    } else { // This was the initial tutorial being skipped
        window.initializeGameApp(null); // Properly initialize a new game
    }
});
// --- Game Initialization Trigger (This is the Master Switch!) ---
// This function will be called by index.html when both the DOM and Firebase are fully ready.
// It's exposed globally for index.html to call.
window.initializeGameApp = (puzzleToLoad = null) => { // Added puzzleToLoad parameter
    console.log("initializeGameApp() called from index.html.");
    initializeGame(puzzleToLoad); // Pass the puzzleToLoad to initializeGame
    loadLeaderboard();
};

// --- DOM Content Loaded Listener (Starts the Firebase & Game Readiness/Tutorial Check) ---
// This makes sure our script waits for the webpage to be fully loaded and Firebase ready.
document.addEventListener('DOMContentLoaded', () => {
    console.log("DOMContentLoaded fired. Script.js waiting for Firebase globals...");

    const checkFirebaseGlobalsInterval = setInterval(() => {
        // Check if ALL necessary global Firebase variables are available
        if (window.firebaseReady && window.firestoreDb && window.appId && window.currentUserId) {
            clearInterval(checkFirebaseGlobalsInterval); // Stop checking once everything is ready
            console.log("All Firebase globals are ready. Proceeding with game initialization or tutorial.");

            // Check if tutorial has been seen before using localStorage
            const tutorialSeen = localStorage.getItem('wordMorphTutorialSeen');
            if (tutorialSeen === 'true') {
                window.initializeGameApp(null); // Explicitly start with daily puzzle (no override)
            } else {
                currentTutorialStep = 0; // Reset to first step
                showTutorialStep(); // Show tutorial if not seen
            }
        } else {
            console.log("Waiting for Firebase globals to be fully available...");
        }
    }, 50); // Check every 50 milliseconds
});
